// 声明 proto 语法版本，固定值

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: blog/social.proto

// proto 包名

package socialrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分页请求参数
type PageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	Sorts         []string               `protobuf:"bytes,3,rep,name=sorts,proto3" json:"sorts,omitempty"`                        // 排序字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageReq) Reset() {
	*x = PageReq{}
	mi := &file_blog_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageReq) ProtoMessage() {}

func (x *PageReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageReq.ProtoReflect.Descriptor instead.
func (*PageReq) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{0}
}

func (x *PageReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageReq) GetSorts() []string {
	if x != nil {
		return x.Sorts
	}
	return nil
}

// 分页响应参数
type PageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`                       // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResp) Reset() {
	*x = PageResp{}
	mi := &file_blog_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResp) ProtoMessage() {}

func (x *PageResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResp.ProtoReflect.Descriptor instead.
func (*PageResp) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{1}
}

func (x *PageResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageResp) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ************* 友链管理 *************
type Friend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                     // id
	LinkName      string                 `protobuf:"bytes,2,opt,name=link_name,json=linkName,proto3" json:"link_name,omitempty"`          // 链接名
	LinkAvatar    string                 `protobuf:"bytes,3,opt,name=link_avatar,json=linkAvatar,proto3" json:"link_avatar,omitempty"`    // 链接头像
	LinkAddress   string                 `protobuf:"bytes,4,opt,name=link_address,json=linkAddress,proto3" json:"link_address,omitempty"` // 链接地址
	LinkIntro     string                 `protobuf:"bytes,5,opt,name=link_intro,json=linkIntro,proto3" json:"link_intro,omitempty"`       // 链接介绍
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`      // 创建时间
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`      // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Friend) Reset() {
	*x = Friend{}
	mi := &file_blog_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Friend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend) ProtoMessage() {}

func (x *Friend) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend.ProtoReflect.Descriptor instead.
func (*Friend) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{2}
}

func (x *Friend) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Friend) GetLinkName() string {
	if x != nil {
		return x.LinkName
	}
	return ""
}

func (x *Friend) GetLinkAvatar() string {
	if x != nil {
		return x.LinkAvatar
	}
	return ""
}

func (x *Friend) GetLinkAddress() string {
	if x != nil {
		return x.LinkAddress
	}
	return ""
}

func (x *Friend) GetLinkIntro() string {
	if x != nil {
		return x.LinkIntro
	}
	return ""
}

func (x *Friend) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Friend) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type AddFriendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                     // id
	LinkName      string                 `protobuf:"bytes,2,opt,name=link_name,json=linkName,proto3" json:"link_name,omitempty"`          // 链接名
	LinkAvatar    string                 `protobuf:"bytes,3,opt,name=link_avatar,json=linkAvatar,proto3" json:"link_avatar,omitempty"`    // 链接头像
	LinkAddress   string                 `protobuf:"bytes,4,opt,name=link_address,json=linkAddress,proto3" json:"link_address,omitempty"` // 链接地址
	LinkIntro     string                 `protobuf:"bytes,5,opt,name=link_intro,json=linkIntro,proto3" json:"link_intro,omitempty"`       // 链接介绍
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFriendReq) Reset() {
	*x = AddFriendReq{}
	mi := &file_blog_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendReq) ProtoMessage() {}

func (x *AddFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendReq.ProtoReflect.Descriptor instead.
func (*AddFriendReq) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{3}
}

func (x *AddFriendReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddFriendReq) GetLinkName() string {
	if x != nil {
		return x.LinkName
	}
	return ""
}

func (x *AddFriendReq) GetLinkAvatar() string {
	if x != nil {
		return x.LinkAvatar
	}
	return ""
}

func (x *AddFriendReq) GetLinkAddress() string {
	if x != nil {
		return x.LinkAddress
	}
	return ""
}

func (x *AddFriendReq) GetLinkIntro() string {
	if x != nil {
		return x.LinkIntro
	}
	return ""
}

type AddFriendResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friend        *Friend                `protobuf:"bytes,1,opt,name=friend,proto3" json:"friend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFriendResp) Reset() {
	*x = AddFriendResp{}
	mi := &file_blog_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFriendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendResp) ProtoMessage() {}

func (x *AddFriendResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendResp.ProtoReflect.Descriptor instead.
func (*AddFriendResp) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{4}
}

func (x *AddFriendResp) GetFriend() *Friend {
	if x != nil {
		return x.Friend
	}
	return nil
}

type UpdateFriendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                     // id
	LinkName      string                 `protobuf:"bytes,2,opt,name=link_name,json=linkName,proto3" json:"link_name,omitempty"`          // 链接名
	LinkAvatar    string                 `protobuf:"bytes,3,opt,name=link_avatar,json=linkAvatar,proto3" json:"link_avatar,omitempty"`    // 链接头像
	LinkAddress   string                 `protobuf:"bytes,4,opt,name=link_address,json=linkAddress,proto3" json:"link_address,omitempty"` // 链接地址
	LinkIntro     string                 `protobuf:"bytes,5,opt,name=link_intro,json=linkIntro,proto3" json:"link_intro,omitempty"`       // 链接介绍
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFriendReq) Reset() {
	*x = UpdateFriendReq{}
	mi := &file_blog_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFriendReq) ProtoMessage() {}

func (x *UpdateFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFriendReq.ProtoReflect.Descriptor instead.
func (*UpdateFriendReq) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFriendReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateFriendReq) GetLinkName() string {
	if x != nil {
		return x.LinkName
	}
	return ""
}

func (x *UpdateFriendReq) GetLinkAvatar() string {
	if x != nil {
		return x.LinkAvatar
	}
	return ""
}

func (x *UpdateFriendReq) GetLinkAddress() string {
	if x != nil {
		return x.LinkAddress
	}
	return ""
}

func (x *UpdateFriendReq) GetLinkIntro() string {
	if x != nil {
		return x.LinkIntro
	}
	return ""
}

type UpdateFriendResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friend        *Friend                `protobuf:"bytes,1,opt,name=friend,proto3" json:"friend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFriendResp) Reset() {
	*x = UpdateFriendResp{}
	mi := &file_blog_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFriendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFriendResp) ProtoMessage() {}

func (x *UpdateFriendResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFriendResp.ProtoReflect.Descriptor instead.
func (*UpdateFriendResp) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateFriendResp) GetFriend() *Friend {
	if x != nil {
		return x.Friend
	}
	return nil
}

type DeletesFriendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"` // id列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletesFriendReq) Reset() {
	*x = DeletesFriendReq{}
	mi := &file_blog_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletesFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletesFriendReq) ProtoMessage() {}

func (x *DeletesFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletesFriendReq.ProtoReflect.Descriptor instead.
func (*DeletesFriendReq) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{7}
}

func (x *DeletesFriendReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeletesFriendResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int64                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"` // 成功数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletesFriendResp) Reset() {
	*x = DeletesFriendResp{}
	mi := &file_blog_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletesFriendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletesFriendResp) ProtoMessage() {}

func (x *DeletesFriendResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletesFriendResp.ProtoReflect.Descriptor instead.
func (*DeletesFriendResp) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{8}
}

func (x *DeletesFriendResp) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

type FindFriendListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paginate      *PageReq               `protobuf:"bytes,1,opt,name=paginate,proto3" json:"paginate,omitempty"`                 // 分页参数
	LinkName      string                 `protobuf:"bytes,2,opt,name=link_name,json=linkName,proto3" json:"link_name,omitempty"` // 链接名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindFriendListReq) Reset() {
	*x = FindFriendListReq{}
	mi := &file_blog_social_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindFriendListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindFriendListReq) ProtoMessage() {}

func (x *FindFriendListReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindFriendListReq.ProtoReflect.Descriptor instead.
func (*FindFriendListReq) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{9}
}

func (x *FindFriendListReq) GetPaginate() *PageReq {
	if x != nil {
		return x.Paginate
	}
	return nil
}

func (x *FindFriendListReq) GetLinkName() string {
	if x != nil {
		return x.LinkName
	}
	return ""
}

type FindFriendListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PageResp              `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"` // 分页信息
	List          []*Friend              `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindFriendListResp) Reset() {
	*x = FindFriendListResp{}
	mi := &file_blog_social_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindFriendListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindFriendListResp) ProtoMessage() {}

func (x *FindFriendListResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindFriendListResp.ProtoReflect.Descriptor instead.
func (*FindFriendListResp) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{10}
}

func (x *FindFriendListResp) GetPagination() *PageResp {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *FindFriendListResp) GetList() []*Friend {
	if x != nil {
		return x.List
	}
	return nil
}

// ************* 说说管理 *************
type Talk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                          // 说说id
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                     // 用户id
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                                 // 说说内容
	ImgList       []string               `protobuf:"bytes,4,rep,name=img_list,json=imgList,proto3" json:"img_list,omitempty"`                  // 图片URL列表
	IsTop         int64                  `protobuf:"varint,5,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`                       // 是否置顶
	Status        int64                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`                                  // 状态 1.公开 2.私密
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`           // 创建时间
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`           // 更新时间
	LikeCount     int64                  `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`           // 点赞量
	CommentCount  int64                  `protobuf:"varint,10,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"` // 评论量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Talk) Reset() {
	*x = Talk{}
	mi := &file_blog_social_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Talk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Talk) ProtoMessage() {}

func (x *Talk) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Talk.ProtoReflect.Descriptor instead.
func (*Talk) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{11}
}

func (x *Talk) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Talk) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Talk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Talk) GetImgList() []string {
	if x != nil {
		return x.ImgList
	}
	return nil
}

func (x *Talk) GetIsTop() int64 {
	if x != nil {
		return x.IsTop
	}
	return 0
}

func (x *Talk) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Talk) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Talk) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Talk) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Talk) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

type AddTalkReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                         // 说说id
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // 用户id
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                // 说说内容
	ImgList       []string               `protobuf:"bytes,4,rep,name=img_list,json=imgList,proto3" json:"img_list,omitempty"` // 图片URL列表
	IsTop         int64                  `protobuf:"varint,5,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`      // 是否置顶
	Status        int64                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`                 // 状态 1.公开 2.私密
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTalkReq) Reset() {
	*x = AddTalkReq{}
	mi := &file_blog_social_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTalkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTalkReq) ProtoMessage() {}

func (x *AddTalkReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTalkReq.ProtoReflect.Descriptor instead.
func (*AddTalkReq) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{12}
}

func (x *AddTalkReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddTalkReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddTalkReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddTalkReq) GetImgList() []string {
	if x != nil {
		return x.ImgList
	}
	return nil
}

func (x *AddTalkReq) GetIsTop() int64 {
	if x != nil {
		return x.IsTop
	}
	return 0
}

func (x *AddTalkReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AddTalkResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Talk          *Talk                  `protobuf:"bytes,1,opt,name=talk,proto3" json:"talk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTalkResp) Reset() {
	*x = AddTalkResp{}
	mi := &file_blog_social_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTalkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTalkResp) ProtoMessage() {}

func (x *AddTalkResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTalkResp.ProtoReflect.Descriptor instead.
func (*AddTalkResp) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{13}
}

func (x *AddTalkResp) GetTalk() *Talk {
	if x != nil {
		return x.Talk
	}
	return nil
}

type UpdateTalkReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                         // 说说id
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // 用户id
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                // 说说内容
	ImgList       []string               `protobuf:"bytes,4,rep,name=img_list,json=imgList,proto3" json:"img_list,omitempty"` // 图片URL列表
	IsTop         int64                  `protobuf:"varint,5,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`      // 是否置顶
	Status        int64                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`                 // 状态 1.公开 2.私密
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTalkReq) Reset() {
	*x = UpdateTalkReq{}
	mi := &file_blog_social_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTalkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTalkReq) ProtoMessage() {}

func (x *UpdateTalkReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTalkReq.ProtoReflect.Descriptor instead.
func (*UpdateTalkReq) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateTalkReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTalkReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateTalkReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateTalkReq) GetImgList() []string {
	if x != nil {
		return x.ImgList
	}
	return nil
}

func (x *UpdateTalkReq) GetIsTop() int64 {
	if x != nil {
		return x.IsTop
	}
	return 0
}

func (x *UpdateTalkReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateTalkResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Talk          *Talk                  `protobuf:"bytes,1,opt,name=talk,proto3" json:"talk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTalkResp) Reset() {
	*x = UpdateTalkResp{}
	mi := &file_blog_social_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTalkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTalkResp) ProtoMessage() {}

func (x *UpdateTalkResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTalkResp.ProtoReflect.Descriptor instead.
func (*UpdateTalkResp) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateTalkResp) GetTalk() *Talk {
	if x != nil {
		return x.Talk
	}
	return nil
}

type DeletesTalkReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"` // id列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletesTalkReq) Reset() {
	*x = DeletesTalkReq{}
	mi := &file_blog_social_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletesTalkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletesTalkReq) ProtoMessage() {}

func (x *DeletesTalkReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletesTalkReq.ProtoReflect.Descriptor instead.
func (*DeletesTalkReq) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{16}
}

func (x *DeletesTalkReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeletesTalkResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int64                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"` // 成功数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletesTalkResp) Reset() {
	*x = DeletesTalkResp{}
	mi := &file_blog_social_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletesTalkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletesTalkResp) ProtoMessage() {}

func (x *DeletesTalkResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletesTalkResp.ProtoReflect.Descriptor instead.
func (*DeletesTalkResp) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{17}
}

func (x *DeletesTalkResp) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

type GetTalkReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 说说id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTalkReq) Reset() {
	*x = GetTalkReq{}
	mi := &file_blog_social_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTalkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTalkReq) ProtoMessage() {}

func (x *GetTalkReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTalkReq.ProtoReflect.Descriptor instead.
func (*GetTalkReq) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{18}
}

func (x *GetTalkReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTalkResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Talk          *Talk                  `protobuf:"bytes,1,opt,name=talk,proto3" json:"talk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTalkResp) Reset() {
	*x = GetTalkResp{}
	mi := &file_blog_social_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTalkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTalkResp) ProtoMessage() {}

func (x *GetTalkResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTalkResp.ProtoReflect.Descriptor instead.
func (*GetTalkResp) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{19}
}

func (x *GetTalkResp) GetTalk() *Talk {
	if x != nil {
		return x.Talk
	}
	return nil
}

type FindTalkListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paginate      *PageReq               `protobuf:"bytes,1,opt,name=paginate,proto3" json:"paginate,omitempty"` // 分页参数
	Status        int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`    // 状态 1.公开 2.私密
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindTalkListReq) Reset() {
	*x = FindTalkListReq{}
	mi := &file_blog_social_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindTalkListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTalkListReq) ProtoMessage() {}

func (x *FindTalkListReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTalkListReq.ProtoReflect.Descriptor instead.
func (*FindTalkListReq) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{20}
}

func (x *FindTalkListReq) GetPaginate() *PageReq {
	if x != nil {
		return x.Paginate
	}
	return nil
}

func (x *FindTalkListReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type FindTalkListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PageResp              `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"` // 分页信息
	List          []*Talk                `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindTalkListResp) Reset() {
	*x = FindTalkListResp{}
	mi := &file_blog_social_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindTalkListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTalkListResp) ProtoMessage() {}

func (x *FindTalkListResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTalkListResp.ProtoReflect.Descriptor instead.
func (*FindTalkListResp) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{21}
}

func (x *FindTalkListResp) GetPagination() *PageResp {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *FindTalkListResp) GetList() []*Talk {
	if x != nil {
		return x.List
	}
	return nil
}

type LikeTalkReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 说说id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeTalkReq) Reset() {
	*x = LikeTalkReq{}
	mi := &file_blog_social_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeTalkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeTalkReq) ProtoMessage() {}

func (x *LikeTalkReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeTalkReq.ProtoReflect.Descriptor instead.
func (*LikeTalkReq) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{22}
}

func (x *LikeTalkReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LikeTalkResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeTalkResp) Reset() {
	*x = LikeTalkResp{}
	mi := &file_blog_social_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeTalkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeTalkResp) ProtoMessage() {}

func (x *LikeTalkResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeTalkResp.ProtoReflect.Descriptor instead.
func (*LikeTalkResp) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{23}
}

type FindUserLikeTalkReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserLikeTalkReq) Reset() {
	*x = FindUserLikeTalkReq{}
	mi := &file_blog_social_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserLikeTalkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserLikeTalkReq) ProtoMessage() {}

func (x *FindUserLikeTalkReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserLikeTalkReq.ProtoReflect.Descriptor instead.
func (*FindUserLikeTalkReq) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{24}
}

func (x *FindUserLikeTalkReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FindUserLikeTalkResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikeTalkList  []int64                `protobuf:"varint,1,rep,packed,name=like_talk_list,json=likeTalkList,proto3" json:"like_talk_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserLikeTalkResp) Reset() {
	*x = FindUserLikeTalkResp{}
	mi := &file_blog_social_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserLikeTalkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserLikeTalkResp) ProtoMessage() {}

func (x *FindUserLikeTalkResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_social_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserLikeTalkResp.ProtoReflect.Descriptor instead.
func (*FindUserLikeTalkResp) Descriptor() ([]byte, []int) {
	return file_blog_social_proto_rawDescGZIP(), []int{25}
}

func (x *FindUserLikeTalkResp) GetLikeTalkList() []int64 {
	if x != nil {
		return x.LikeTalkList
	}
	return nil
}

var File_blog_social_proto protoreflect.FileDescriptor

const file_blog_social_proto_rawDesc = "" +
	"\n" +
	"\x11blog/social.proto\x12\tsocialrpc\"P\n" +
	"\aPageReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x14\n" +
	"\x05sorts\x18\x03 \x03(\tR\x05sorts\"Q\n" +
	"\bPageResp\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"\xd6\x01\n" +
	"\x06Friend\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tlink_name\x18\x02 \x01(\tR\blinkName\x12\x1f\n" +
	"\vlink_avatar\x18\x03 \x01(\tR\n" +
	"linkAvatar\x12!\n" +
	"\flink_address\x18\x04 \x01(\tR\vlinkAddress\x12\x1d\n" +
	"\n" +
	"link_intro\x18\x05 \x01(\tR\tlinkIntro\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\x9e\x01\n" +
	"\fAddFriendReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tlink_name\x18\x02 \x01(\tR\blinkName\x12\x1f\n" +
	"\vlink_avatar\x18\x03 \x01(\tR\n" +
	"linkAvatar\x12!\n" +
	"\flink_address\x18\x04 \x01(\tR\vlinkAddress\x12\x1d\n" +
	"\n" +
	"link_intro\x18\x05 \x01(\tR\tlinkIntro\":\n" +
	"\rAddFriendResp\x12)\n" +
	"\x06friend\x18\x01 \x01(\v2\x11.socialrpc.FriendR\x06friend\"\xa1\x01\n" +
	"\x0fUpdateFriendReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tlink_name\x18\x02 \x01(\tR\blinkName\x12\x1f\n" +
	"\vlink_avatar\x18\x03 \x01(\tR\n" +
	"linkAvatar\x12!\n" +
	"\flink_address\x18\x04 \x01(\tR\vlinkAddress\x12\x1d\n" +
	"\n" +
	"link_intro\x18\x05 \x01(\tR\tlinkIntro\"=\n" +
	"\x10UpdateFriendResp\x12)\n" +
	"\x06friend\x18\x01 \x01(\v2\x11.socialrpc.FriendR\x06friend\"$\n" +
	"\x10DeletesFriendReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"8\n" +
	"\x11DeletesFriendResp\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x03R\fsuccessCount\"`\n" +
	"\x11FindFriendListReq\x12.\n" +
	"\bpaginate\x18\x01 \x01(\v2\x12.socialrpc.PageReqR\bpaginate\x12\x1b\n" +
	"\tlink_name\x18\x02 \x01(\tR\blinkName\"p\n" +
	"\x12FindFriendListResp\x123\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x13.socialrpc.PageRespR\n" +
	"pagination\x12%\n" +
	"\x04list\x18\x02 \x03(\v2\x11.socialrpc.FriendR\x04list\"\x95\x02\n" +
	"\x04Talk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x19\n" +
	"\bimg_list\x18\x04 \x03(\tR\aimgList\x12\x15\n" +
	"\x06is_top\x18\x05 \x01(\x03R\x05isTop\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x03R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"like_count\x18\t \x01(\x03R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\n" +
	" \x01(\x03R\fcommentCount\"\x99\x01\n" +
	"\n" +
	"AddTalkReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x19\n" +
	"\bimg_list\x18\x04 \x03(\tR\aimgList\x12\x15\n" +
	"\x06is_top\x18\x05 \x01(\x03R\x05isTop\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x03R\x06status\"2\n" +
	"\vAddTalkResp\x12#\n" +
	"\x04talk\x18\x01 \x01(\v2\x0f.socialrpc.TalkR\x04talk\"\x9c\x01\n" +
	"\rUpdateTalkReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x19\n" +
	"\bimg_list\x18\x04 \x03(\tR\aimgList\x12\x15\n" +
	"\x06is_top\x18\x05 \x01(\x03R\x05isTop\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x03R\x06status\"5\n" +
	"\x0eUpdateTalkResp\x12#\n" +
	"\x04talk\x18\x01 \x01(\v2\x0f.socialrpc.TalkR\x04talk\"\"\n" +
	"\x0eDeletesTalkReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"6\n" +
	"\x0fDeletesTalkResp\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x03R\fsuccessCount\"\x1c\n" +
	"\n" +
	"GetTalkReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"2\n" +
	"\vGetTalkResp\x12#\n" +
	"\x04talk\x18\x01 \x01(\v2\x0f.socialrpc.TalkR\x04talk\"Y\n" +
	"\x0fFindTalkListReq\x12.\n" +
	"\bpaginate\x18\x01 \x01(\v2\x12.socialrpc.PageReqR\bpaginate\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\"l\n" +
	"\x10FindTalkListResp\x123\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x13.socialrpc.PageRespR\n" +
	"pagination\x12#\n" +
	"\x04list\x18\x02 \x03(\v2\x0f.socialrpc.TalkR\x04list\"\x1d\n" +
	"\vLikeTalkReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x0e\n" +
	"\fLikeTalkResp\".\n" +
	"\x13FindUserLikeTalkReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"<\n" +
	"\x14FindUserLikeTalkResp\x12$\n" +
	"\x0elike_talk_list\x18\x01 \x03(\x03R\flikeTalkList2\x87\x06\n" +
	"\tSocialRpc\x12>\n" +
	"\tAddFriend\x12\x17.socialrpc.AddFriendReq\x1a\x18.socialrpc.AddFriendResp\x12G\n" +
	"\fUpdateFriend\x12\x1a.socialrpc.UpdateFriendReq\x1a\x1b.socialrpc.UpdateFriendResp\x12J\n" +
	"\rDeletesFriend\x12\x1b.socialrpc.DeletesFriendReq\x1a\x1c.socialrpc.DeletesFriendResp\x12M\n" +
	"\x0eFindFriendList\x12\x1c.socialrpc.FindFriendListReq\x1a\x1d.socialrpc.FindFriendListResp\x128\n" +
	"\aAddTalk\x12\x15.socialrpc.AddTalkReq\x1a\x16.socialrpc.AddTalkResp\x12A\n" +
	"\n" +
	"UpdateTalk\x12\x18.socialrpc.UpdateTalkReq\x1a\x19.socialrpc.UpdateTalkResp\x12D\n" +
	"\vDeletesTalk\x12\x19.socialrpc.DeletesTalkReq\x1a\x1a.socialrpc.DeletesTalkResp\x128\n" +
	"\aGetTalk\x12\x15.socialrpc.GetTalkReq\x1a\x16.socialrpc.GetTalkResp\x12G\n" +
	"\fFindTalkList\x12\x1a.socialrpc.FindTalkListReq\x1a\x1b.socialrpc.FindTalkListResp\x12;\n" +
	"\bLikeTalk\x12\x16.socialrpc.LikeTalkReq\x1a\x17.socialrpc.LikeTalkResp\x12S\n" +
	"\x10FindUserLikeTalk\x12\x1e.socialrpc.FindUserLikeTalkReq\x1a\x1f.socialrpc.FindUserLikeTalkRespB\rZ\v./socialrpcb\x06proto3"

var (
	file_blog_social_proto_rawDescOnce sync.Once
	file_blog_social_proto_rawDescData []byte
)

func file_blog_social_proto_rawDescGZIP() []byte {
	file_blog_social_proto_rawDescOnce.Do(func() {
		file_blog_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_social_proto_rawDesc), len(file_blog_social_proto_rawDesc)))
	})
	return file_blog_social_proto_rawDescData
}

var file_blog_social_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_blog_social_proto_goTypes = []any{
	(*PageReq)(nil),              // 0: socialrpc.PageReq
	(*PageResp)(nil),             // 1: socialrpc.PageResp
	(*Friend)(nil),               // 2: socialrpc.Friend
	(*AddFriendReq)(nil),         // 3: socialrpc.AddFriendReq
	(*AddFriendResp)(nil),        // 4: socialrpc.AddFriendResp
	(*UpdateFriendReq)(nil),      // 5: socialrpc.UpdateFriendReq
	(*UpdateFriendResp)(nil),     // 6: socialrpc.UpdateFriendResp
	(*DeletesFriendReq)(nil),     // 7: socialrpc.DeletesFriendReq
	(*DeletesFriendResp)(nil),    // 8: socialrpc.DeletesFriendResp
	(*FindFriendListReq)(nil),    // 9: socialrpc.FindFriendListReq
	(*FindFriendListResp)(nil),   // 10: socialrpc.FindFriendListResp
	(*Talk)(nil),                 // 11: socialrpc.Talk
	(*AddTalkReq)(nil),           // 12: socialrpc.AddTalkReq
	(*AddTalkResp)(nil),          // 13: socialrpc.AddTalkResp
	(*UpdateTalkReq)(nil),        // 14: socialrpc.UpdateTalkReq
	(*UpdateTalkResp)(nil),       // 15: socialrpc.UpdateTalkResp
	(*DeletesTalkReq)(nil),       // 16: socialrpc.DeletesTalkReq
	(*DeletesTalkResp)(nil),      // 17: socialrpc.DeletesTalkResp
	(*GetTalkReq)(nil),           // 18: socialrpc.GetTalkReq
	(*GetTalkResp)(nil),          // 19: socialrpc.GetTalkResp
	(*FindTalkListReq)(nil),      // 20: socialrpc.FindTalkListReq
	(*FindTalkListResp)(nil),     // 21: socialrpc.FindTalkListResp
	(*LikeTalkReq)(nil),          // 22: socialrpc.LikeTalkReq
	(*LikeTalkResp)(nil),         // 23: socialrpc.LikeTalkResp
	(*FindUserLikeTalkReq)(nil),  // 24: socialrpc.FindUserLikeTalkReq
	(*FindUserLikeTalkResp)(nil), // 25: socialrpc.FindUserLikeTalkResp
}
var file_blog_social_proto_depIdxs = []int32{
	2,  // 0: socialrpc.AddFriendResp.friend:type_name -> socialrpc.Friend
	2,  // 1: socialrpc.UpdateFriendResp.friend:type_name -> socialrpc.Friend
	0,  // 2: socialrpc.FindFriendListReq.paginate:type_name -> socialrpc.PageReq
	1,  // 3: socialrpc.FindFriendListResp.pagination:type_name -> socialrpc.PageResp
	2,  // 4: socialrpc.FindFriendListResp.list:type_name -> socialrpc.Friend
	11, // 5: socialrpc.AddTalkResp.talk:type_name -> socialrpc.Talk
	11, // 6: socialrpc.UpdateTalkResp.talk:type_name -> socialrpc.Talk
	11, // 7: socialrpc.GetTalkResp.talk:type_name -> socialrpc.Talk
	0,  // 8: socialrpc.FindTalkListReq.paginate:type_name -> socialrpc.PageReq
	1,  // 9: socialrpc.FindTalkListResp.pagination:type_name -> socialrpc.PageResp
	11, // 10: socialrpc.FindTalkListResp.list:type_name -> socialrpc.Talk
	3,  // 11: socialrpc.SocialRpc.AddFriend:input_type -> socialrpc.AddFriendReq
	5,  // 12: socialrpc.SocialRpc.UpdateFriend:input_type -> socialrpc.UpdateFriendReq
	7,  // 13: socialrpc.SocialRpc.DeletesFriend:input_type -> socialrpc.DeletesFriendReq
	9,  // 14: socialrpc.SocialRpc.FindFriendList:input_type -> socialrpc.FindFriendListReq
	12, // 15: socialrpc.SocialRpc.AddTalk:input_type -> socialrpc.AddTalkReq
	14, // 16: socialrpc.SocialRpc.UpdateTalk:input_type -> socialrpc.UpdateTalkReq
	16, // 17: socialrpc.SocialRpc.DeletesTalk:input_type -> socialrpc.DeletesTalkReq
	18, // 18: socialrpc.SocialRpc.GetTalk:input_type -> socialrpc.GetTalkReq
	20, // 19: socialrpc.SocialRpc.FindTalkList:input_type -> socialrpc.FindTalkListReq
	22, // 20: socialrpc.SocialRpc.LikeTalk:input_type -> socialrpc.LikeTalkReq
	24, // 21: socialrpc.SocialRpc.FindUserLikeTalk:input_type -> socialrpc.FindUserLikeTalkReq
	4,  // 22: socialrpc.SocialRpc.AddFriend:output_type -> socialrpc.AddFriendResp
	6,  // 23: socialrpc.SocialRpc.UpdateFriend:output_type -> socialrpc.UpdateFriendResp
	8,  // 24: socialrpc.SocialRpc.DeletesFriend:output_type -> socialrpc.DeletesFriendResp
	10, // 25: socialrpc.SocialRpc.FindFriendList:output_type -> socialrpc.FindFriendListResp
	13, // 26: socialrpc.SocialRpc.AddTalk:output_type -> socialrpc.AddTalkResp
	15, // 27: socialrpc.SocialRpc.UpdateTalk:output_type -> socialrpc.UpdateTalkResp
	17, // 28: socialrpc.SocialRpc.DeletesTalk:output_type -> socialrpc.DeletesTalkResp
	19, // 29: socialrpc.SocialRpc.GetTalk:output_type -> socialrpc.GetTalkResp
	21, // 30: socialrpc.SocialRpc.FindTalkList:output_type -> socialrpc.FindTalkListResp
	23, // 31: socialrpc.SocialRpc.LikeTalk:output_type -> socialrpc.LikeTalkResp
	25, // 32: socialrpc.SocialRpc.FindUserLikeTalk:output_type -> socialrpc.FindUserLikeTalkResp
	22, // [22:33] is the sub-list for method output_type
	11, // [11:22] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_blog_social_proto_init() }
func file_blog_social_proto_init() {
	if File_blog_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_social_proto_rawDesc), len(file_blog_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_social_proto_goTypes,
		DependencyIndexes: file_blog_social_proto_depIdxs,
		MessageInfos:      file_blog_social_proto_msgTypes,
	}.Build()
	File_blog_social_proto = out.File
	file_blog_social_proto_goTypes = nil
	file_blog_social_proto_depIdxs = nil
}
