// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type LoginLogPageResp struct {
	PageMeta
	List []*LoginLogBackVO `json:"list"`
}

type QueryLoginLogReq struct {
	PageQuery
	UserId string `json:"user_id,optional"` // 用户id
}
