// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type OperationLogPageResp struct {
	PageMeta
	List []*OperationLogBackVO `json:"list"`
}

type QueryOperationLogReq struct {
	PageQuery
}
