// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tArticleFieldNames          = builder.RawFieldNames(&TArticle{}, true)
	tArticleRows                = strings.Join(tArticleFieldNames, ",")
	tArticleRowsExpectAutoSet   = strings.Join(stringx.Remove(tArticleFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	tArticleRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(tArticleFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicTArticleIdPrefix = "cache:public:tArticle:id:"
)

type (
	tArticleModel interface {
		Insert(ctx context.Context, data *TArticle) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TArticle, error)
		Update(ctx context.Context, data *TArticle) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTArticleModel struct {
		sqlc.CachedConn
		table string
	}

	TArticle struct {
		Id int64 `db:"id"` // id

		UserId string `db:"user_id"` // 作者

		CategoryId int64 `db:"category_id"` // 文章分类

		ArticleCover string `db:"article_cover"` // 文章缩略图

		ArticleTitle string `db:"article_title"` // 标题

		ArticleContent string `db:"article_content"` // 内容

		ArticleType int64 `db:"article_type"` // 文章类型 1原创 2转载 3翻译

		OriginalUrl string `db:"original_url"` // 原文链接

		Tags []string `db:"tags"` // 标签列表

		Metadata string `db:"metadata"` // 文章扩展元数据

		IsTop bool `db:"is_top"` // 是否置顶 0否 1是

		IsDelete bool `db:"is_delete"` // 是否删除 0否 1是

		Status int64 `db:"status"` // 状态值 1公开 2私密 3草稿 4评论可见

		LikeCount int64 `db:"like_count"` // 点赞数

		ViewCount int64 `db:"view_count"` // 查看数

		CreatedAt time.Time `db:"created_at"` // 发表时间

		UpdatedAt time.Time `db:"updated_at"` // 更新时间

	}
)

func newTArticleModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTArticleModel {
	return &defaultTArticleModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."t_article"`,
	}
}

func (m *defaultTArticleModel) Delete(ctx context.Context, id int64) error {
	publicTArticleIdKey := fmt.Sprintf("%s%v", cachePublicTArticleIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicTArticleIdKey)
	return err
}

func (m *defaultTArticleModel) FindOne(ctx context.Context, id int64) (*TArticle, error) {
	publicTArticleIdKey := fmt.Sprintf("%s%v", cachePublicTArticleIdPrefix, id)
	var resp TArticle
	err := m.QueryRowCtx(ctx, &resp, publicTArticleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", tArticleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTArticleModel) Insert(ctx context.Context, data *TArticle) (sql.Result, error) {
	publicTArticleIdKey := fmt.Sprintf("%s%v", cachePublicTArticleIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)", m.table, tArticleRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.CategoryId, data.ArticleCover, data.ArticleTitle, data.ArticleContent, data.ArticleType, data.OriginalUrl, data.Tags, data.Metadata, data.IsTop, data.IsDelete, data.Status, data.LikeCount, data.ViewCount)
	}, publicTArticleIdKey)
	return ret, err
}

func (m *defaultTArticleModel) Update(ctx context.Context, data *TArticle) error {
	publicTArticleIdKey := fmt.Sprintf("%s%v", cachePublicTArticleIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, tArticleRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.CategoryId, data.ArticleCover, data.ArticleTitle, data.ArticleContent, data.ArticleType, data.OriginalUrl, data.Tags, data.Metadata, data.IsTop, data.IsDelete, data.Status, data.LikeCount, data.ViewCount)
	}, publicTArticleIdKey)
	return err
}

func (m *defaultTArticleModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicTArticleIdPrefix, primary)
}

func (m *defaultTArticleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", tArticleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTArticleModel) tableName() string {
	return m.table
}
