// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tFriendFieldNames          = builder.RawFieldNames(&TFriend{}, true)
	tFriendRows                = strings.Join(tFriendFieldNames, ",")
	tFriendRowsExpectAutoSet   = strings.Join(stringx.Remove(tFriendFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	tFriendRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(tFriendFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicTFriendIdPrefix       = "cache:public:tFriend:id:"
	cachePublicTFriendLinkNamePrefix = "cache:public:tFriend:linkName:"
)

type (
	tFriendModel interface {
		Insert(ctx context.Context, data *TFriend) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TFriend, error)
		FindOneByLinkName(ctx context.Context, linkName string) (*TFriend, error)
		Update(ctx context.Context, data *TFriend) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTFriendModel struct {
		sqlc.CachedConn
		table string
	}

	TFriend struct {
		Id          int64     `db:"id"`           // id
		LinkName    string    `db:"link_name"`    // 链接名
		LinkAvatar  string    `db:"link_avatar"`  // 链接头像
		LinkAddress string    `db:"link_address"` // 链接地址
		LinkIntro   string    `db:"link_intro"`   // 链接介绍
		CreatedAt   time.Time `db:"created_at"`   // 创建时间
		UpdatedAt   time.Time `db:"updated_at"`   // 更新时间
	}
)

func newTFriendModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTFriendModel {
	return &defaultTFriendModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."t_friend"`,
	}
}

func (m *defaultTFriendModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	publicTFriendIdKey := fmt.Sprintf("%s%v", cachePublicTFriendIdPrefix, id)
	publicTFriendLinkNameKey := fmt.Sprintf("%s%v", cachePublicTFriendLinkNamePrefix, data.LinkName)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicTFriendIdKey, publicTFriendLinkNameKey)
	return err
}

func (m *defaultTFriendModel) FindOne(ctx context.Context, id int64) (*TFriend, error) {
	publicTFriendIdKey := fmt.Sprintf("%s%v", cachePublicTFriendIdPrefix, id)
	var resp TFriend
	err := m.QueryRowCtx(ctx, &resp, publicTFriendIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", tFriendRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTFriendModel) FindOneByLinkName(ctx context.Context, linkName string) (*TFriend, error) {
	publicTFriendLinkNameKey := fmt.Sprintf("%s%v", cachePublicTFriendLinkNamePrefix, linkName)
	var resp TFriend
	err := m.QueryRowIndexCtx(ctx, &resp, publicTFriendLinkNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where link_name = $1 limit 1", tFriendRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, linkName); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTFriendModel) Insert(ctx context.Context, data *TFriend) (sql.Result, error) {
	publicTFriendIdKey := fmt.Sprintf("%s%v", cachePublicTFriendIdPrefix, data.Id)
	publicTFriendLinkNameKey := fmt.Sprintf("%s%v", cachePublicTFriendLinkNamePrefix, data.LinkName)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, tFriendRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.LinkName, data.LinkAvatar, data.LinkAddress, data.LinkIntro)
	}, publicTFriendIdKey, publicTFriendLinkNameKey)
	return ret, err
}

func (m *defaultTFriendModel) Update(ctx context.Context, newData *TFriend) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	publicTFriendIdKey := fmt.Sprintf("%s%v", cachePublicTFriendIdPrefix, data.Id)
	publicTFriendLinkNameKey := fmt.Sprintf("%s%v", cachePublicTFriendLinkNamePrefix, data.LinkName)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, tFriendRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Id, newData.LinkName, newData.LinkAvatar, newData.LinkAddress, newData.LinkIntro)
	}, publicTFriendIdKey, publicTFriendLinkNameKey)
	return err
}

func (m *defaultTFriendModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicTFriendIdPrefix, primary)
}

func (m *defaultTFriendModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", tFriendRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTFriendModel) tableName() string {
	return m.table
}
