// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tMenuFieldNames          = builder.RawFieldNames(&TMenu{}, true)
	tMenuRows                = strings.Join(tMenuFieldNames, ",")
	tMenuRowsExpectAutoSet   = strings.Join(stringx.Remove(tMenuFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	tMenuRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(tMenuFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicTMenuIdPrefix       = "cache:public:tMenu:id:"
	cachePublicTMenuPathPermPrefix = "cache:public:tMenu:path:perm:"
)

type (
	tMenuModel interface {
		Insert(ctx context.Context, data *TMenu) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TMenu, error)
		FindOneByPathPerm(ctx context.Context, path string, perm string) (*TMenu, error)
		Update(ctx context.Context, data *TMenu) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTMenuModel struct {
		sqlc.CachedConn
		table string
	}

	TMenu struct {
		Id int64 `db:"id"` // 主键

		ParentId int64 `db:"parent_id"` // 父id

		Path string `db:"path"` // 路由路径

		Name string `db:"name"` // 路由名称

		Component string `db:"component"` // 路由组件

		Redirect string `db:"redirect"` // 路由重定向

		Type string `db:"type"` // 菜单类型

		Title string `db:"title"` // 菜单标题

		Icon string `db:"icon"` // 菜单图标

		Rank int64 `db:"rank"` // 排序

		Perm string `db:"perm"` // 权限标识

		Params string `db:"params"` // 路由参数

		KeepAlive bool `db:"keep_alive"` // 是否缓存

		AlwaysShow bool `db:"always_show"` // 是否一直显示菜单

		Visible bool `db:"visible"` // 菜单是否可见

		Status bool `db:"status"` // 是否禁用

		Extra string `db:"extra"` // 菜单元数据

		CreatedAt time.Time `db:"created_at"` // 创建时间

		UpdatedAt time.Time `db:"updated_at"` // 更新时间

	}
)

func newTMenuModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTMenuModel {
	return &defaultTMenuModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."t_menu"`,
	}
}

func (m *defaultTMenuModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	publicTMenuIdKey := fmt.Sprintf("%s%v", cachePublicTMenuIdPrefix, id)
	publicTMenuPathPermKey := fmt.Sprintf("%s%v:%v", cachePublicTMenuPathPermPrefix, data.Path, data.Perm)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicTMenuIdKey, publicTMenuPathPermKey)
	return err
}

func (m *defaultTMenuModel) FindOne(ctx context.Context, id int64) (*TMenu, error) {
	publicTMenuIdKey := fmt.Sprintf("%s%v", cachePublicTMenuIdPrefix, id)
	var resp TMenu
	err := m.QueryRowCtx(ctx, &resp, publicTMenuIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", tMenuRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTMenuModel) FindOneByPathPerm(ctx context.Context, path string, perm string) (*TMenu, error) {
	publicTMenuPathPermKey := fmt.Sprintf("%s%v:%v", cachePublicTMenuPathPermPrefix, path, perm)
	var resp TMenu
	err := m.QueryRowIndexCtx(ctx, &resp, publicTMenuPathPermKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where path = $1 and perm = $2 limit 1", tMenuRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, path, perm); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTMenuModel) Insert(ctx context.Context, data *TMenu) (sql.Result, error) {
	publicTMenuIdKey := fmt.Sprintf("%s%v", cachePublicTMenuIdPrefix, data.Id)
	publicTMenuPathPermKey := fmt.Sprintf("%s%v:%v", cachePublicTMenuPathPermPrefix, data.Path, data.Perm)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)", m.table, tMenuRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ParentId, data.Path, data.Name, data.Component, data.Redirect, data.Type, data.Title, data.Icon, data.Rank, data.Perm, data.Params, data.KeepAlive, data.AlwaysShow, data.Visible, data.Status, data.Extra)
	}, publicTMenuIdKey, publicTMenuPathPermKey)
	return ret, err
}

func (m *defaultTMenuModel) Update(ctx context.Context, newData *TMenu) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	publicTMenuIdKey := fmt.Sprintf("%s%v", cachePublicTMenuIdPrefix, data.Id)
	publicTMenuPathPermKey := fmt.Sprintf("%s%v:%v", cachePublicTMenuPathPermPrefix, data.Path, data.Perm)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, tMenuRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Id, newData.ParentId, newData.Path, newData.Name, newData.Component, newData.Redirect, newData.Type, newData.Title, newData.Icon, newData.Rank, newData.Perm, newData.Params, newData.KeepAlive, newData.AlwaysShow, newData.Visible, newData.Status, newData.Extra)
	}, publicTMenuIdKey, publicTMenuPathPermKey)
	return err
}

func (m *defaultTMenuModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicTMenuIdPrefix, primary)
}

func (m *defaultTMenuModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", tMenuRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTMenuModel) tableName() string {
	return m.table
}
