// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tRoleMenuFieldNames          = builder.RawFieldNames(&TRoleMenu{}, true)
	tRoleMenuRows                = strings.Join(tRoleMenuFieldNames, ",")
	tRoleMenuRowsExpectAutoSet   = strings.Join(stringx.Remove(tRoleMenuFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	tRoleMenuRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(tRoleMenuFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	tRoleMenuModel interface {
		Insert(ctx context.Context, data *TRoleMenu) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TRoleMenu, error)
		Update(ctx context.Context, data *TRoleMenu) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTRoleMenuModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TRoleMenu struct {
		Id int64 `db:"id"` // 主键id

		RoleId int64 `db:"role_id"` // 角色id

		MenuId int64 `db:"menu_id"` // 菜单id

	}
)

func newTRoleMenuModel(conn sqlx.SqlConn) *defaultTRoleMenuModel {
	return &defaultTRoleMenuModel{
		conn:  conn,
		table: `"public"."t_role_menu"`,
	}
}

func (m *defaultTRoleMenuModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTRoleMenuModel) FindOne(ctx context.Context, id int64) (*TRoleMenu, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", tRoleMenuRows, m.table)
	var resp TRoleMenu
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTRoleMenuModel) Insert(ctx context.Context, data *TRoleMenu) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2)", m.table, tRoleMenuRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RoleId, data.MenuId)
	return ret, err
}

func (m *defaultTRoleMenuModel) Update(ctx context.Context, data *TRoleMenu) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, tRoleMenuRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.RoleId, data.MenuId)
	return err
}

func (m *defaultTRoleMenuModel) tableName() string {
	return m.table
}
