// 声明 proto 语法版本，固定值

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: blog/article.proto

// proto 包名

package articlerpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArticleRpc_AnalysisArticle_FullMethodName        = "/articlerpc.ArticleRpc/AnalysisArticle"
	ArticleRpc_AddArticleVisits_FullMethodName       = "/articlerpc.ArticleRpc/AddArticleVisits"
	ArticleRpc_AddArticle_FullMethodName             = "/articlerpc.ArticleRpc/AddArticle"
	ArticleRpc_UpdateArticle_FullMethodName          = "/articlerpc.ArticleRpc/UpdateArticle"
	ArticleRpc_UpdateArticleDelete_FullMethodName    = "/articlerpc.ArticleRpc/UpdateArticleDelete"
	ArticleRpc_UpdateArticleTop_FullMethodName       = "/articlerpc.ArticleRpc/UpdateArticleTop"
	ArticleRpc_DeletesArticle_FullMethodName         = "/articlerpc.ArticleRpc/DeletesArticle"
	ArticleRpc_GetArticle_FullMethodName             = "/articlerpc.ArticleRpc/GetArticle"
	ArticleRpc_GetArticleRelation_FullMethodName     = "/articlerpc.ArticleRpc/GetArticleRelation"
	ArticleRpc_FindArticleList_FullMethodName        = "/articlerpc.ArticleRpc/FindArticleList"
	ArticleRpc_FindArticlePreviewList_FullMethodName = "/articlerpc.ArticleRpc/FindArticlePreviewList"
	ArticleRpc_LikeArticle_FullMethodName            = "/articlerpc.ArticleRpc/LikeArticle"
	ArticleRpc_FindUserLikeArticle_FullMethodName    = "/articlerpc.ArticleRpc/FindUserLikeArticle"
	ArticleRpc_AddCategory_FullMethodName            = "/articlerpc.ArticleRpc/AddCategory"
	ArticleRpc_UpdateCategory_FullMethodName         = "/articlerpc.ArticleRpc/UpdateCategory"
	ArticleRpc_GetCategory_FullMethodName            = "/articlerpc.ArticleRpc/GetCategory"
	ArticleRpc_DeletesCategory_FullMethodName        = "/articlerpc.ArticleRpc/DeletesCategory"
	ArticleRpc_FindCategoryList_FullMethodName       = "/articlerpc.ArticleRpc/FindCategoryList"
)

// ArticleRpcClient is the client API for ArticleRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// article服务
type ArticleRpcClient interface {
	// 分析文章数量
	AnalysisArticle(ctx context.Context, in *AnalysisArticleReq, opts ...grpc.CallOption) (*AnalysisArticleResp, error)
	// 添加文章访问量
	AddArticleVisits(ctx context.Context, in *AddArticleVisitsReq, opts ...grpc.CallOption) (*AddArticleVisitsResp, error)
	// 创建文章
	AddArticle(ctx context.Context, in *AddArticleReq, opts ...grpc.CallOption) (*AddArticleResp, error)
	// 更新文章
	UpdateArticle(ctx context.Context, in *UpdateArticleReq, opts ...grpc.CallOption) (*UpdateArticleResp, error)
	// 更新文章删除
	UpdateArticleDelete(ctx context.Context, in *UpdateArticleDeleteReq, opts ...grpc.CallOption) (*UpdateArticleDeleteResp, error)
	// 更新文章置顶
	UpdateArticleTop(ctx context.Context, in *UpdateArticleTopReq, opts ...grpc.CallOption) (*UpdateArticleTopResp, error)
	// 删除文章
	DeletesArticle(ctx context.Context, in *DeletesArticleReq, opts ...grpc.CallOption) (*DeletesArticleResp, error)
	// 查询文章
	GetArticle(ctx context.Context, in *GetArticleReq, opts ...grpc.CallOption) (*GetArticleResp, error)
	// 查询关联文章
	GetArticleRelation(ctx context.Context, in *GetArticleRelationReq, opts ...grpc.CallOption) (*GetArticleRelationResp, error)
	// 查询文章列表
	FindArticleList(ctx context.Context, in *FindArticleListReq, opts ...grpc.CallOption) (*FindArticleListResp, error)
	// 查询文章列表
	FindArticlePreviewList(ctx context.Context, in *FindArticleListReq, opts ...grpc.CallOption) (*FindArticlePreviewListResp, error)
	// 点赞文章
	LikeArticle(ctx context.Context, in *LikeArticleReq, opts ...grpc.CallOption) (*LikeArticleResp, error)
	// 用户点赞的文章
	FindUserLikeArticle(ctx context.Context, in *FindUserLikeArticleReq, opts ...grpc.CallOption) (*FindLikeArticleResp, error)
	// 创建文章分类
	AddCategory(ctx context.Context, in *AddCategoryReq, opts ...grpc.CallOption) (*AddCategoryResp, error)
	// 更新文章分类
	UpdateCategory(ctx context.Context, in *UpdateCategoryReq, opts ...grpc.CallOption) (*UpdateCategoryResp, error)
	// 查询文章分类
	GetCategory(ctx context.Context, in *GetCategoryReq, opts ...grpc.CallOption) (*GetCategoryResp, error)
	// 删除文章分类
	DeletesCategory(ctx context.Context, in *DeletesCategoryReq, opts ...grpc.CallOption) (*DeletesCategoryResp, error)
	// 查询文章分类列表
	FindCategoryList(ctx context.Context, in *FindCategoryListReq, opts ...grpc.CallOption) (*FindCategoryListResp, error)
}

type articleRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleRpcClient(cc grpc.ClientConnInterface) ArticleRpcClient {
	return &articleRpcClient{cc}
}

func (c *articleRpcClient) AnalysisArticle(ctx context.Context, in *AnalysisArticleReq, opts ...grpc.CallOption) (*AnalysisArticleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalysisArticleResp)
	err := c.cc.Invoke(ctx, ArticleRpc_AnalysisArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcClient) AddArticleVisits(ctx context.Context, in *AddArticleVisitsReq, opts ...grpc.CallOption) (*AddArticleVisitsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddArticleVisitsResp)
	err := c.cc.Invoke(ctx, ArticleRpc_AddArticleVisits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcClient) AddArticle(ctx context.Context, in *AddArticleReq, opts ...grpc.CallOption) (*AddArticleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddArticleResp)
	err := c.cc.Invoke(ctx, ArticleRpc_AddArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcClient) UpdateArticle(ctx context.Context, in *UpdateArticleReq, opts ...grpc.CallOption) (*UpdateArticleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateArticleResp)
	err := c.cc.Invoke(ctx, ArticleRpc_UpdateArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcClient) UpdateArticleDelete(ctx context.Context, in *UpdateArticleDeleteReq, opts ...grpc.CallOption) (*UpdateArticleDeleteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateArticleDeleteResp)
	err := c.cc.Invoke(ctx, ArticleRpc_UpdateArticleDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcClient) UpdateArticleTop(ctx context.Context, in *UpdateArticleTopReq, opts ...grpc.CallOption) (*UpdateArticleTopResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateArticleTopResp)
	err := c.cc.Invoke(ctx, ArticleRpc_UpdateArticleTop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcClient) DeletesArticle(ctx context.Context, in *DeletesArticleReq, opts ...grpc.CallOption) (*DeletesArticleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletesArticleResp)
	err := c.cc.Invoke(ctx, ArticleRpc_DeletesArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcClient) GetArticle(ctx context.Context, in *GetArticleReq, opts ...grpc.CallOption) (*GetArticleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticleResp)
	err := c.cc.Invoke(ctx, ArticleRpc_GetArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcClient) GetArticleRelation(ctx context.Context, in *GetArticleRelationReq, opts ...grpc.CallOption) (*GetArticleRelationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticleRelationResp)
	err := c.cc.Invoke(ctx, ArticleRpc_GetArticleRelation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcClient) FindArticleList(ctx context.Context, in *FindArticleListReq, opts ...grpc.CallOption) (*FindArticleListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindArticleListResp)
	err := c.cc.Invoke(ctx, ArticleRpc_FindArticleList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcClient) FindArticlePreviewList(ctx context.Context, in *FindArticleListReq, opts ...grpc.CallOption) (*FindArticlePreviewListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindArticlePreviewListResp)
	err := c.cc.Invoke(ctx, ArticleRpc_FindArticlePreviewList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcClient) LikeArticle(ctx context.Context, in *LikeArticleReq, opts ...grpc.CallOption) (*LikeArticleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeArticleResp)
	err := c.cc.Invoke(ctx, ArticleRpc_LikeArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcClient) FindUserLikeArticle(ctx context.Context, in *FindUserLikeArticleReq, opts ...grpc.CallOption) (*FindLikeArticleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindLikeArticleResp)
	err := c.cc.Invoke(ctx, ArticleRpc_FindUserLikeArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcClient) AddCategory(ctx context.Context, in *AddCategoryReq, opts ...grpc.CallOption) (*AddCategoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCategoryResp)
	err := c.cc.Invoke(ctx, ArticleRpc_AddCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcClient) UpdateCategory(ctx context.Context, in *UpdateCategoryReq, opts ...grpc.CallOption) (*UpdateCategoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCategoryResp)
	err := c.cc.Invoke(ctx, ArticleRpc_UpdateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcClient) GetCategory(ctx context.Context, in *GetCategoryReq, opts ...grpc.CallOption) (*GetCategoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryResp)
	err := c.cc.Invoke(ctx, ArticleRpc_GetCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcClient) DeletesCategory(ctx context.Context, in *DeletesCategoryReq, opts ...grpc.CallOption) (*DeletesCategoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletesCategoryResp)
	err := c.cc.Invoke(ctx, ArticleRpc_DeletesCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcClient) FindCategoryList(ctx context.Context, in *FindCategoryListReq, opts ...grpc.CallOption) (*FindCategoryListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindCategoryListResp)
	err := c.cc.Invoke(ctx, ArticleRpc_FindCategoryList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleRpcServer is the server API for ArticleRpc service.
// All implementations must embed UnimplementedArticleRpcServer
// for forward compatibility.
//
// article服务
type ArticleRpcServer interface {
	// 分析文章数量
	AnalysisArticle(context.Context, *AnalysisArticleReq) (*AnalysisArticleResp, error)
	// 添加文章访问量
	AddArticleVisits(context.Context, *AddArticleVisitsReq) (*AddArticleVisitsResp, error)
	// 创建文章
	AddArticle(context.Context, *AddArticleReq) (*AddArticleResp, error)
	// 更新文章
	UpdateArticle(context.Context, *UpdateArticleReq) (*UpdateArticleResp, error)
	// 更新文章删除
	UpdateArticleDelete(context.Context, *UpdateArticleDeleteReq) (*UpdateArticleDeleteResp, error)
	// 更新文章置顶
	UpdateArticleTop(context.Context, *UpdateArticleTopReq) (*UpdateArticleTopResp, error)
	// 删除文章
	DeletesArticle(context.Context, *DeletesArticleReq) (*DeletesArticleResp, error)
	// 查询文章
	GetArticle(context.Context, *GetArticleReq) (*GetArticleResp, error)
	// 查询关联文章
	GetArticleRelation(context.Context, *GetArticleRelationReq) (*GetArticleRelationResp, error)
	// 查询文章列表
	FindArticleList(context.Context, *FindArticleListReq) (*FindArticleListResp, error)
	// 查询文章列表
	FindArticlePreviewList(context.Context, *FindArticleListReq) (*FindArticlePreviewListResp, error)
	// 点赞文章
	LikeArticle(context.Context, *LikeArticleReq) (*LikeArticleResp, error)
	// 用户点赞的文章
	FindUserLikeArticle(context.Context, *FindUserLikeArticleReq) (*FindLikeArticleResp, error)
	// 创建文章分类
	AddCategory(context.Context, *AddCategoryReq) (*AddCategoryResp, error)
	// 更新文章分类
	UpdateCategory(context.Context, *UpdateCategoryReq) (*UpdateCategoryResp, error)
	// 查询文章分类
	GetCategory(context.Context, *GetCategoryReq) (*GetCategoryResp, error)
	// 删除文章分类
	DeletesCategory(context.Context, *DeletesCategoryReq) (*DeletesCategoryResp, error)
	// 查询文章分类列表
	FindCategoryList(context.Context, *FindCategoryListReq) (*FindCategoryListResp, error)
	mustEmbedUnimplementedArticleRpcServer()
}

// UnimplementedArticleRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArticleRpcServer struct{}

func (UnimplementedArticleRpcServer) AnalysisArticle(context.Context, *AnalysisArticleReq) (*AnalysisArticleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalysisArticle not implemented")
}
func (UnimplementedArticleRpcServer) AddArticleVisits(context.Context, *AddArticleVisitsReq) (*AddArticleVisitsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddArticleVisits not implemented")
}
func (UnimplementedArticleRpcServer) AddArticle(context.Context, *AddArticleReq) (*AddArticleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddArticle not implemented")
}
func (UnimplementedArticleRpcServer) UpdateArticle(context.Context, *UpdateArticleReq) (*UpdateArticleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateArticle not implemented")
}
func (UnimplementedArticleRpcServer) UpdateArticleDelete(context.Context, *UpdateArticleDeleteReq) (*UpdateArticleDeleteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateArticleDelete not implemented")
}
func (UnimplementedArticleRpcServer) UpdateArticleTop(context.Context, *UpdateArticleTopReq) (*UpdateArticleTopResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateArticleTop not implemented")
}
func (UnimplementedArticleRpcServer) DeletesArticle(context.Context, *DeletesArticleReq) (*DeletesArticleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletesArticle not implemented")
}
func (UnimplementedArticleRpcServer) GetArticle(context.Context, *GetArticleReq) (*GetArticleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArticle not implemented")
}
func (UnimplementedArticleRpcServer) GetArticleRelation(context.Context, *GetArticleRelationReq) (*GetArticleRelationResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArticleRelation not implemented")
}
func (UnimplementedArticleRpcServer) FindArticleList(context.Context, *FindArticleListReq) (*FindArticleListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FindArticleList not implemented")
}
func (UnimplementedArticleRpcServer) FindArticlePreviewList(context.Context, *FindArticleListReq) (*FindArticlePreviewListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FindArticlePreviewList not implemented")
}
func (UnimplementedArticleRpcServer) LikeArticle(context.Context, *LikeArticleReq) (*LikeArticleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeArticle not implemented")
}
func (UnimplementedArticleRpcServer) FindUserLikeArticle(context.Context, *FindUserLikeArticleReq) (*FindLikeArticleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FindUserLikeArticle not implemented")
}
func (UnimplementedArticleRpcServer) AddCategory(context.Context, *AddCategoryReq) (*AddCategoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCategory not implemented")
}
func (UnimplementedArticleRpcServer) UpdateCategory(context.Context, *UpdateCategoryReq) (*UpdateCategoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCategory not implemented")
}
func (UnimplementedArticleRpcServer) GetCategory(context.Context, *GetCategoryReq) (*GetCategoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategory not implemented")
}
func (UnimplementedArticleRpcServer) DeletesCategory(context.Context, *DeletesCategoryReq) (*DeletesCategoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletesCategory not implemented")
}
func (UnimplementedArticleRpcServer) FindCategoryList(context.Context, *FindCategoryListReq) (*FindCategoryListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FindCategoryList not implemented")
}
func (UnimplementedArticleRpcServer) mustEmbedUnimplementedArticleRpcServer() {}
func (UnimplementedArticleRpcServer) testEmbeddedByValue()                    {}

// UnsafeArticleRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleRpcServer will
// result in compilation errors.
type UnsafeArticleRpcServer interface {
	mustEmbedUnimplementedArticleRpcServer()
}

func RegisterArticleRpcServer(s grpc.ServiceRegistrar, srv ArticleRpcServer) {
	// If the following call panics, it indicates UnimplementedArticleRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArticleRpc_ServiceDesc, srv)
}

func _ArticleRpc_AnalysisArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalysisArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServer).AnalysisArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleRpc_AnalysisArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServer).AnalysisArticle(ctx, req.(*AnalysisArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpc_AddArticleVisits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddArticleVisitsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServer).AddArticleVisits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleRpc_AddArticleVisits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServer).AddArticleVisits(ctx, req.(*AddArticleVisitsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpc_AddArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServer).AddArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleRpc_AddArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServer).AddArticle(ctx, req.(*AddArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpc_UpdateArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServer).UpdateArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleRpc_UpdateArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServer).UpdateArticle(ctx, req.(*UpdateArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpc_UpdateArticleDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateArticleDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServer).UpdateArticleDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleRpc_UpdateArticleDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServer).UpdateArticleDelete(ctx, req.(*UpdateArticleDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpc_UpdateArticleTop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateArticleTopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServer).UpdateArticleTop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleRpc_UpdateArticleTop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServer).UpdateArticleTop(ctx, req.(*UpdateArticleTopReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpc_DeletesArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletesArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServer).DeletesArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleRpc_DeletesArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServer).DeletesArticle(ctx, req.(*DeletesArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpc_GetArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServer).GetArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleRpc_GetArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServer).GetArticle(ctx, req.(*GetArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpc_GetArticleRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleRelationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServer).GetArticleRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleRpc_GetArticleRelation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServer).GetArticleRelation(ctx, req.(*GetArticleRelationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpc_FindArticleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindArticleListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServer).FindArticleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleRpc_FindArticleList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServer).FindArticleList(ctx, req.(*FindArticleListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpc_FindArticlePreviewList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindArticleListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServer).FindArticlePreviewList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleRpc_FindArticlePreviewList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServer).FindArticlePreviewList(ctx, req.(*FindArticleListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpc_LikeArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServer).LikeArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleRpc_LikeArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServer).LikeArticle(ctx, req.(*LikeArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpc_FindUserLikeArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserLikeArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServer).FindUserLikeArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleRpc_FindUserLikeArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServer).FindUserLikeArticle(ctx, req.(*FindUserLikeArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpc_AddCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServer).AddCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleRpc_AddCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServer).AddCategory(ctx, req.(*AddCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpc_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleRpc_UpdateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServer).UpdateCategory(ctx, req.(*UpdateCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpc_GetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServer).GetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleRpc_GetCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServer).GetCategory(ctx, req.(*GetCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpc_DeletesCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletesCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServer).DeletesCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleRpc_DeletesCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServer).DeletesCategory(ctx, req.(*DeletesCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpc_FindCategoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCategoryListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServer).FindCategoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleRpc_FindCategoryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServer).FindCategoryList(ctx, req.(*FindCategoryListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticleRpc_ServiceDesc is the grpc.ServiceDesc for ArticleRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticleRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "articlerpc.ArticleRpc",
	HandlerType: (*ArticleRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalysisArticle",
			Handler:    _ArticleRpc_AnalysisArticle_Handler,
		},
		{
			MethodName: "AddArticleVisits",
			Handler:    _ArticleRpc_AddArticleVisits_Handler,
		},
		{
			MethodName: "AddArticle",
			Handler:    _ArticleRpc_AddArticle_Handler,
		},
		{
			MethodName: "UpdateArticle",
			Handler:    _ArticleRpc_UpdateArticle_Handler,
		},
		{
			MethodName: "UpdateArticleDelete",
			Handler:    _ArticleRpc_UpdateArticleDelete_Handler,
		},
		{
			MethodName: "UpdateArticleTop",
			Handler:    _ArticleRpc_UpdateArticleTop_Handler,
		},
		{
			MethodName: "DeletesArticle",
			Handler:    _ArticleRpc_DeletesArticle_Handler,
		},
		{
			MethodName: "GetArticle",
			Handler:    _ArticleRpc_GetArticle_Handler,
		},
		{
			MethodName: "GetArticleRelation",
			Handler:    _ArticleRpc_GetArticleRelation_Handler,
		},
		{
			MethodName: "FindArticleList",
			Handler:    _ArticleRpc_FindArticleList_Handler,
		},
		{
			MethodName: "FindArticlePreviewList",
			Handler:    _ArticleRpc_FindArticlePreviewList_Handler,
		},
		{
			MethodName: "LikeArticle",
			Handler:    _ArticleRpc_LikeArticle_Handler,
		},
		{
			MethodName: "FindUserLikeArticle",
			Handler:    _ArticleRpc_FindUserLikeArticle_Handler,
		},
		{
			MethodName: "AddCategory",
			Handler:    _ArticleRpc_AddCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _ArticleRpc_UpdateCategory_Handler,
		},
		{
			MethodName: "GetCategory",
			Handler:    _ArticleRpc_GetCategory_Handler,
		},
		{
			MethodName: "DeletesCategory",
			Handler:    _ArticleRpc_DeletesCategory_Handler,
		},
		{
			MethodName: "FindCategoryList",
			Handler:    _ArticleRpc_FindCategoryList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog/article.proto",
}
