// 声明 proto 语法版本，固定值

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: blog/article.proto

// proto 包名

package articlerpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分页请求参数
type PageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	Sorts         []string               `protobuf:"bytes,3,rep,name=sorts,proto3" json:"sorts,omitempty"`                        // 排序字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageReq) Reset() {
	*x = PageReq{}
	mi := &file_blog_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageReq) ProtoMessage() {}

func (x *PageReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageReq.ProtoReflect.Descriptor instead.
func (*PageReq) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{0}
}

func (x *PageReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageReq) GetSorts() []string {
	if x != nil {
		return x.Sorts
	}
	return nil
}

// 分页响应参数
type PageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`                       // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResp) Reset() {
	*x = PageResp{}
	mi := &file_blog_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResp) ProtoMessage() {}

func (x *PageResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResp.ProtoReflect.Descriptor instead.
func (*PageResp) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{1}
}

func (x *PageResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageResp) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 文章预览信息
type ArticlePreview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // id
	ArticleCover  string                 `protobuf:"bytes,4,opt,name=article_cover,json=articleCover,proto3" json:"article_cover,omitempty"` // 文章缩略图
	ArticleTitle  string                 `protobuf:"bytes,5,opt,name=article_title,json=articleTitle,proto3" json:"article_title,omitempty"` // 标题
	CreatedAt     int64                  `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`        // 发表时间
	LikeCount     int64                  `protobuf:"varint,16,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`        // 点赞数
	ViewCount     int64                  `protobuf:"varint,17,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`        // 查看数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticlePreview) Reset() {
	*x = ArticlePreview{}
	mi := &file_blog_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticlePreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticlePreview) ProtoMessage() {}

func (x *ArticlePreview) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticlePreview.ProtoReflect.Descriptor instead.
func (*ArticlePreview) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{2}
}

func (x *ArticlePreview) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticlePreview) GetArticleCover() string {
	if x != nil {
		return x.ArticleCover
	}
	return ""
}

func (x *ArticlePreview) GetArticleTitle() string {
	if x != nil {
		return x.ArticleTitle
	}
	return ""
}

func (x *ArticlePreview) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ArticlePreview) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *ArticlePreview) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

// 文章分类信息
type ArticleCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // id
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"` // 分类名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleCategory) Reset() {
	*x = ArticleCategory{}
	mi := &file_blog_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleCategory) ProtoMessage() {}

func (x *ArticleCategory) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleCategory.ProtoReflect.Descriptor instead.
func (*ArticleCategory) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{3}
}

func (x *ArticleCategory) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleCategory) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

// 文章标签信息
type ArticleTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagName       string                 `protobuf:"bytes,1,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"` // 标签名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleTag) Reset() {
	*x = ArticleTag{}
	mi := &file_blog_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleTag) ProtoMessage() {}

func (x *ArticleTag) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleTag.ProtoReflect.Descriptor instead.
func (*ArticleTag) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{4}
}

func (x *ArticleTag) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

// 文章详情信息
type ArticleDetails struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                              // id
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // 作者
	CategoryId     int64                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`            // 文章分类
	ArticleCover   string                 `protobuf:"bytes,4,opt,name=article_cover,json=articleCover,proto3" json:"article_cover,omitempty"`       // 文章缩略图
	ArticleTitle   string                 `protobuf:"bytes,5,opt,name=article_title,json=articleTitle,proto3" json:"article_title,omitempty"`       // 标题
	ArticleContent string                 `protobuf:"bytes,6,opt,name=article_content,json=articleContent,proto3" json:"article_content,omitempty"` // 内容
	ArticleType    int64                  `protobuf:"varint,7,opt,name=article_type,json=articleType,proto3" json:"article_type,omitempty"`         // 文章类型 1原创 2转载 3翻译
	OriginalUrl    string                 `protobuf:"bytes,8,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`          // 原文链接
	IsTop          bool                   `protobuf:"varint,9,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`                           // 是否置顶 1是
	IsDelete       bool                   `protobuf:"varint,10,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`                 // 是否删除 1是
	Status         int64                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`                                     // 状态值 1公开 2私密 3草稿 4已删除
	CreatedAt      int64                  `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`              // 发表时间
	UpdatedAt      int64                  `protobuf:"varint,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`              // 更新时间
	Category       *ArticleCategory       `protobuf:"bytes,14,opt,name=category,proto3" json:"category,omitempty"`                                  // 分类
	TagList        []*ArticleTag          `protobuf:"bytes,15,rep,name=tag_list,json=tagList,proto3" json:"tag_list,omitempty"`                     // 标签
	LikeCount      int64                  `protobuf:"varint,16,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`              // 点赞数
	ViewCount      int64                  `protobuf:"varint,17,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`              // 查看数量
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ArticleDetails) Reset() {
	*x = ArticleDetails{}
	mi := &file_blog_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleDetails) ProtoMessage() {}

func (x *ArticleDetails) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleDetails.ProtoReflect.Descriptor instead.
func (*ArticleDetails) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{5}
}

func (x *ArticleDetails) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleDetails) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ArticleDetails) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ArticleDetails) GetArticleCover() string {
	if x != nil {
		return x.ArticleCover
	}
	return ""
}

func (x *ArticleDetails) GetArticleTitle() string {
	if x != nil {
		return x.ArticleTitle
	}
	return ""
}

func (x *ArticleDetails) GetArticleContent() string {
	if x != nil {
		return x.ArticleContent
	}
	return ""
}

func (x *ArticleDetails) GetArticleType() int64 {
	if x != nil {
		return x.ArticleType
	}
	return 0
}

func (x *ArticleDetails) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *ArticleDetails) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

func (x *ArticleDetails) GetIsDelete() bool {
	if x != nil {
		return x.IsDelete
	}
	return false
}

func (x *ArticleDetails) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ArticleDetails) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ArticleDetails) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ArticleDetails) GetCategory() *ArticleCategory {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *ArticleDetails) GetTagList() []*ArticleTag {
	if x != nil {
		return x.TagList
	}
	return nil
}

func (x *ArticleDetails) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *ArticleDetails) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

// 分类预览信息
type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // id
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"` // 分类名
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`         // 创建时间
	UpdatedAt     int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`         // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_blog_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{6}
}

func (x *Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *Category) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Category) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 分类详情信息
type CategoryDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                         // id
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`  // 分类名
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`          // 创建时间
	UpdatedAt     int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`          // 更新时间
	ArticleCount  int64                  `protobuf:"varint,5,opt,name=article_count,json=articleCount,proto3" json:"article_count,omitempty"` // 文章数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryDetails) Reset() {
	*x = CategoryDetails{}
	mi := &file_blog_article_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryDetails) ProtoMessage() {}

func (x *CategoryDetails) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryDetails.ProtoReflect.Descriptor instead.
func (*CategoryDetails) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{7}
}

func (x *CategoryDetails) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryDetails) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CategoryDetails) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CategoryDetails) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *CategoryDetails) GetArticleCount() int64 {
	if x != nil {
		return x.ArticleCount
	}
	return 0
}

// 标签详情信息
type TagDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagName       string                 `protobuf:"bytes,1,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`                 // 标签名
	ArticleCount  int64                  `protobuf:"varint,2,opt,name=article_count,json=articleCount,proto3" json:"article_count,omitempty"` // 文章数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagDetails) Reset() {
	*x = TagDetails{}
	mi := &file_blog_article_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagDetails) ProtoMessage() {}

func (x *TagDetails) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagDetails.ProtoReflect.Descriptor instead.
func (*TagDetails) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{8}
}

func (x *TagDetails) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *TagDetails) GetArticleCount() int64 {
	if x != nil {
		return x.ArticleCount
	}
	return 0
}

// 文章每日统计信息
type ArticleDailyStatistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`    // 日期
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // 数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleDailyStatistics) Reset() {
	*x = ArticleDailyStatistics{}
	mi := &file_blog_article_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleDailyStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleDailyStatistics) ProtoMessage() {}

func (x *ArticleDailyStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleDailyStatistics.ProtoReflect.Descriptor instead.
func (*ArticleDailyStatistics) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{9}
}

func (x *ArticleDailyStatistics) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ArticleDailyStatistics) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// ************* article 相关 *************
type AddArticleReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                              // id
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // 作者
	ArticleCover   string                 `protobuf:"bytes,4,opt,name=article_cover,json=articleCover,proto3" json:"article_cover,omitempty"`       // 文章缩略图
	ArticleTitle   string                 `protobuf:"bytes,5,opt,name=article_title,json=articleTitle,proto3" json:"article_title,omitempty"`       // 标题
	ArticleContent string                 `protobuf:"bytes,6,opt,name=article_content,json=articleContent,proto3" json:"article_content,omitempty"` // 内容
	ArticleType    int64                  `protobuf:"varint,7,opt,name=article_type,json=articleType,proto3" json:"article_type,omitempty"`         // 文章类型 1原创 2转载 3翻译
	OriginalUrl    string                 `protobuf:"bytes,8,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`          // 原文链接
	IsTop          bool                   `protobuf:"varint,9,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`                           // 是否置顶
	Status         int64                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`                                     // 状态值 1 公开 2 私密 3 草稿 4 已删除
	CategoryName   string                 `protobuf:"bytes,15,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`      // 分类名
	TagNameList    []string               `protobuf:"bytes,16,rep,name=tag_name_list,json=tagNameList,proto3" json:"tag_name_list,omitempty"`       // 标签名
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddArticleReq) Reset() {
	*x = AddArticleReq{}
	mi := &file_blog_article_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArticleReq) ProtoMessage() {}

func (x *AddArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArticleReq.ProtoReflect.Descriptor instead.
func (*AddArticleReq) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{10}
}

func (x *AddArticleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddArticleReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddArticleReq) GetArticleCover() string {
	if x != nil {
		return x.ArticleCover
	}
	return ""
}

func (x *AddArticleReq) GetArticleTitle() string {
	if x != nil {
		return x.ArticleTitle
	}
	return ""
}

func (x *AddArticleReq) GetArticleContent() string {
	if x != nil {
		return x.ArticleContent
	}
	return ""
}

func (x *AddArticleReq) GetArticleType() int64 {
	if x != nil {
		return x.ArticleType
	}
	return 0
}

func (x *AddArticleReq) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *AddArticleReq) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

func (x *AddArticleReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddArticleReq) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *AddArticleReq) GetTagNameList() []string {
	if x != nil {
		return x.TagNameList
	}
	return nil
}

type AddArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *ArticlePreview        `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddArticleResp) Reset() {
	*x = AddArticleResp{}
	mi := &file_blog_article_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArticleResp) ProtoMessage() {}

func (x *AddArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArticleResp.ProtoReflect.Descriptor instead.
func (*AddArticleResp) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{11}
}

func (x *AddArticleResp) GetArticle() *ArticlePreview {
	if x != nil {
		return x.Article
	}
	return nil
}

type UpdateArticleReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                              // id
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // 作者
	ArticleCover   string                 `protobuf:"bytes,4,opt,name=article_cover,json=articleCover,proto3" json:"article_cover,omitempty"`       // 文章缩略图
	ArticleTitle   string                 `protobuf:"bytes,5,opt,name=article_title,json=articleTitle,proto3" json:"article_title,omitempty"`       // 标题
	ArticleContent string                 `protobuf:"bytes,6,opt,name=article_content,json=articleContent,proto3" json:"article_content,omitempty"` // 内容
	ArticleType    int64                  `protobuf:"varint,7,opt,name=article_type,json=articleType,proto3" json:"article_type,omitempty"`         // 文章类型 1原创 2转载 3翻译
	OriginalUrl    string                 `protobuf:"bytes,8,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`          // 原文链接
	IsTop          bool                   `protobuf:"varint,9,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`                           // 是否置顶
	Status         int64                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`                                     // 状态值 1 公开 2 私密 3 草稿 4 已删除
	CategoryName   string                 `protobuf:"bytes,15,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`      // 分类名
	TagNameList    []string               `protobuf:"bytes,16,rep,name=tag_name_list,json=tagNameList,proto3" json:"tag_name_list,omitempty"`       // 标签名
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateArticleReq) Reset() {
	*x = UpdateArticleReq{}
	mi := &file_blog_article_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleReq) ProtoMessage() {}

func (x *UpdateArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleReq.ProtoReflect.Descriptor instead.
func (*UpdateArticleReq) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateArticleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateArticleReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateArticleReq) GetArticleCover() string {
	if x != nil {
		return x.ArticleCover
	}
	return ""
}

func (x *UpdateArticleReq) GetArticleTitle() string {
	if x != nil {
		return x.ArticleTitle
	}
	return ""
}

func (x *UpdateArticleReq) GetArticleContent() string {
	if x != nil {
		return x.ArticleContent
	}
	return ""
}

func (x *UpdateArticleReq) GetArticleType() int64 {
	if x != nil {
		return x.ArticleType
	}
	return 0
}

func (x *UpdateArticleReq) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *UpdateArticleReq) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

func (x *UpdateArticleReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateArticleReq) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *UpdateArticleReq) GetTagNameList() []string {
	if x != nil {
		return x.TagNameList
	}
	return nil
}

type UpdateArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *ArticlePreview        `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleResp) Reset() {
	*x = UpdateArticleResp{}
	mi := &file_blog_article_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleResp) ProtoMessage() {}

func (x *UpdateArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleResp.ProtoReflect.Descriptor instead.
func (*UpdateArticleResp) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateArticleResp) GetArticle() *ArticlePreview {
	if x != nil {
		return x.Article
	}
	return nil
}

type UpdateArticleDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     int64                  `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	IsDelete      bool                   `protobuf:"varint,2,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"` // 是否删除
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleDeleteReq) Reset() {
	*x = UpdateArticleDeleteReq{}
	mi := &file_blog_article_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleDeleteReq) ProtoMessage() {}

func (x *UpdateArticleDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleDeleteReq.ProtoReflect.Descriptor instead.
func (*UpdateArticleDeleteReq) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateArticleDeleteReq) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *UpdateArticleDeleteReq) GetIsDelete() bool {
	if x != nil {
		return x.IsDelete
	}
	return false
}

type UpdateArticleDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *ArticlePreview        `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleDeleteResp) Reset() {
	*x = UpdateArticleDeleteResp{}
	mi := &file_blog_article_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleDeleteResp) ProtoMessage() {}

func (x *UpdateArticleDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleDeleteResp.ProtoReflect.Descriptor instead.
func (*UpdateArticleDeleteResp) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateArticleDeleteResp) GetArticle() *ArticlePreview {
	if x != nil {
		return x.Article
	}
	return nil
}

type UpdateArticleTopReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     int64                  `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	IsTop         bool                   `protobuf:"varint,2,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"` // 是否置顶
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleTopReq) Reset() {
	*x = UpdateArticleTopReq{}
	mi := &file_blog_article_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleTopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleTopReq) ProtoMessage() {}

func (x *UpdateArticleTopReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleTopReq.ProtoReflect.Descriptor instead.
func (*UpdateArticleTopReq) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateArticleTopReq) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *UpdateArticleTopReq) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

type UpdateArticleTopResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *ArticlePreview        `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleTopResp) Reset() {
	*x = UpdateArticleTopResp{}
	mi := &file_blog_article_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleTopResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleTopResp) ProtoMessage() {}

func (x *UpdateArticleTopResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleTopResp.ProtoReflect.Descriptor instead.
func (*UpdateArticleTopResp) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateArticleTopResp) GetArticle() *ArticlePreview {
	if x != nil {
		return x.Article
	}
	return nil
}

type GetArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleReq) Reset() {
	*x = GetArticleReq{}
	mi := &file_blog_article_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleReq) ProtoMessage() {}

func (x *GetArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleReq.ProtoReflect.Descriptor instead.
func (*GetArticleReq) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{18}
}

func (x *GetArticleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *ArticleDetails        `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleResp) Reset() {
	*x = GetArticleResp{}
	mi := &file_blog_article_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleResp) ProtoMessage() {}

func (x *GetArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleResp.ProtoReflect.Descriptor instead.
func (*GetArticleResp) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{19}
}

func (x *GetArticleResp) GetArticle() *ArticleDetails {
	if x != nil {
		return x.Article
	}
	return nil
}

type GetArticleRelationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRelationReq) Reset() {
	*x = GetArticleRelationReq{}
	mi := &file_blog_article_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRelationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRelationReq) ProtoMessage() {}

func (x *GetArticleRelationReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRelationReq.ProtoReflect.Descriptor instead.
func (*GetArticleRelationReq) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{20}
}

func (x *GetArticleRelationReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetArticleRelationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Last          *ArticlePreview        `protobuf:"bytes,1,opt,name=last,proto3" json:"last,omitempty"`
	Next          *ArticlePreview        `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	Recommend     []*ArticlePreview      `protobuf:"bytes,3,rep,name=recommend,proto3" json:"recommend,omitempty"`
	Newest        []*ArticlePreview      `protobuf:"bytes,4,rep,name=newest,proto3" json:"newest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRelationResp) Reset() {
	*x = GetArticleRelationResp{}
	mi := &file_blog_article_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRelationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRelationResp) ProtoMessage() {}

func (x *GetArticleRelationResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRelationResp.ProtoReflect.Descriptor instead.
func (*GetArticleRelationResp) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{21}
}

func (x *GetArticleRelationResp) GetLast() *ArticlePreview {
	if x != nil {
		return x.Last
	}
	return nil
}

func (x *GetArticleRelationResp) GetNext() *ArticlePreview {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *GetArticleRelationResp) GetRecommend() []*ArticlePreview {
	if x != nil {
		return x.Recommend
	}
	return nil
}

func (x *GetArticleRelationResp) GetNewest() []*ArticlePreview {
	if x != nil {
		return x.Newest
	}
	return nil
}

type DeletesArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletesArticleReq) Reset() {
	*x = DeletesArticleReq{}
	mi := &file_blog_article_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletesArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletesArticleReq) ProtoMessage() {}

func (x *DeletesArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletesArticleReq.ProtoReflect.Descriptor instead.
func (*DeletesArticleReq) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{22}
}

func (x *DeletesArticleReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeletesArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int64                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletesArticleResp) Reset() {
	*x = DeletesArticleResp{}
	mi := &file_blog_article_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletesArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletesArticleResp) ProtoMessage() {}

func (x *DeletesArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletesArticleResp.ProtoReflect.Descriptor instead.
func (*DeletesArticleResp) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{23}
}

func (x *DeletesArticleResp) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

type AddArticleVisitsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddArticleVisitsReq) Reset() {
	*x = AddArticleVisitsReq{}
	mi := &file_blog_article_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddArticleVisitsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArticleVisitsReq) ProtoMessage() {}

func (x *AddArticleVisitsReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArticleVisitsReq.ProtoReflect.Descriptor instead.
func (*AddArticleVisitsReq) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{24}
}

func (x *AddArticleVisitsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddArticleVisitsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddArticleVisitsResp) Reset() {
	*x = AddArticleVisitsResp{}
	mi := &file_blog_article_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddArticleVisitsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArticleVisitsResp) ProtoMessage() {}

func (x *AddArticleVisitsResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArticleVisitsResp.ProtoReflect.Descriptor instead.
func (*AddArticleVisitsResp) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{25}
}

type LikeArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeArticleReq) Reset() {
	*x = LikeArticleReq{}
	mi := &file_blog_article_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeArticleReq) ProtoMessage() {}

func (x *LikeArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeArticleReq.ProtoReflect.Descriptor instead.
func (*LikeArticleReq) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{26}
}

func (x *LikeArticleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LikeArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeArticleResp) Reset() {
	*x = LikeArticleResp{}
	mi := &file_blog_article_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeArticleResp) ProtoMessage() {}

func (x *LikeArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeArticleResp.ProtoReflect.Descriptor instead.
func (*LikeArticleResp) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{27}
}

type FindUserLikeArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserLikeArticleReq) Reset() {
	*x = FindUserLikeArticleReq{}
	mi := &file_blog_article_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserLikeArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserLikeArticleReq) ProtoMessage() {}

func (x *FindUserLikeArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserLikeArticleReq.ProtoReflect.Descriptor instead.
func (*FindUserLikeArticleReq) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{28}
}

func (x *FindUserLikeArticleReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FindLikeArticleResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LikeArticleList []int64                `protobuf:"varint,1,rep,packed,name=like_article_list,json=likeArticleList,proto3" json:"like_article_list,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FindLikeArticleResp) Reset() {
	*x = FindLikeArticleResp{}
	mi := &file_blog_article_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindLikeArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindLikeArticleResp) ProtoMessage() {}

func (x *FindLikeArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindLikeArticleResp.ProtoReflect.Descriptor instead.
func (*FindLikeArticleResp) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{29}
}

func (x *FindLikeArticleResp) GetLikeArticleList() []int64 {
	if x != nil {
		return x.LikeArticleList
	}
	return nil
}

type FindArticleListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paginate      *PageReq               `protobuf:"bytes,1,opt,name=paginate,proto3" json:"paginate,omitempty"`                             // 分页参数
	ArticleTitle  string                 `protobuf:"bytes,2,opt,name=article_title,json=articleTitle,proto3" json:"article_title,omitempty"` // 标题
	ArticleType   int64                  `protobuf:"varint,3,opt,name=article_type,json=articleType,proto3" json:"article_type,omitempty"`   // 文章类型 1原创 2转载 3翻译
	CategoryName  string                 `protobuf:"bytes,4,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"` // 分类名
	TagName       string                 `protobuf:"bytes,5,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`                // 标签名
	IsTop         *bool                  `protobuf:"varint,6,opt,name=is_top,json=isTop,proto3,oneof" json:"is_top,omitempty"`               // 是否置顶
	IsDelete      *bool                  `protobuf:"varint,7,opt,name=is_delete,json=isDelete,proto3,oneof" json:"is_delete,omitempty"`      // 是否删除
	Status        int64                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`                                // 状态值 1公开 2私密 3草稿 4已删除
	Ids           []int64                `protobuf:"varint,9,rep,packed,name=ids,proto3" json:"ids,omitempty"`                               //文章id列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindArticleListReq) Reset() {
	*x = FindArticleListReq{}
	mi := &file_blog_article_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindArticleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindArticleListReq) ProtoMessage() {}

func (x *FindArticleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindArticleListReq.ProtoReflect.Descriptor instead.
func (*FindArticleListReq) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{30}
}

func (x *FindArticleListReq) GetPaginate() *PageReq {
	if x != nil {
		return x.Paginate
	}
	return nil
}

func (x *FindArticleListReq) GetArticleTitle() string {
	if x != nil {
		return x.ArticleTitle
	}
	return ""
}

func (x *FindArticleListReq) GetArticleType() int64 {
	if x != nil {
		return x.ArticleType
	}
	return 0
}

func (x *FindArticleListReq) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *FindArticleListReq) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *FindArticleListReq) GetIsTop() bool {
	if x != nil && x.IsTop != nil {
		return *x.IsTop
	}
	return false
}

func (x *FindArticleListReq) GetIsDelete() bool {
	if x != nil && x.IsDelete != nil {
		return *x.IsDelete
	}
	return false
}

func (x *FindArticleListReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FindArticleListReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type FindArticleListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PageResp              `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"` // 分页信息
	List          []*ArticleDetails      `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindArticleListResp) Reset() {
	*x = FindArticleListResp{}
	mi := &file_blog_article_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindArticleListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindArticleListResp) ProtoMessage() {}

func (x *FindArticleListResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindArticleListResp.ProtoReflect.Descriptor instead.
func (*FindArticleListResp) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{31}
}

func (x *FindArticleListResp) GetPagination() *PageResp {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *FindArticleListResp) GetList() []*ArticleDetails {
	if x != nil {
		return x.List
	}
	return nil
}

type FindArticlePreviewListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PageResp              `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"` // 分页信息
	List          []*ArticlePreview      `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindArticlePreviewListResp) Reset() {
	*x = FindArticlePreviewListResp{}
	mi := &file_blog_article_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindArticlePreviewListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindArticlePreviewListResp) ProtoMessage() {}

func (x *FindArticlePreviewListResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindArticlePreviewListResp.ProtoReflect.Descriptor instead.
func (*FindArticlePreviewListResp) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{32}
}

func (x *FindArticlePreviewListResp) GetPagination() *PageResp {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *FindArticlePreviewListResp) GetList() []*ArticlePreview {
	if x != nil {
		return x.List
	}
	return nil
}

// ************* category 相关 *************
type AddCategoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // id
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"` // 分类名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCategoryReq) Reset() {
	*x = AddCategoryReq{}
	mi := &file_blog_article_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCategoryReq) ProtoMessage() {}

func (x *AddCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCategoryReq.ProtoReflect.Descriptor instead.
func (*AddCategoryReq) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{33}
}

func (x *AddCategoryReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddCategoryReq) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

type AddCategoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCategoryResp) Reset() {
	*x = AddCategoryResp{}
	mi := &file_blog_article_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCategoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCategoryResp) ProtoMessage() {}

func (x *AddCategoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCategoryResp.ProtoReflect.Descriptor instead.
func (*AddCategoryResp) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{34}
}

func (x *AddCategoryResp) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type UpdateCategoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // id
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"` // 分类名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryReq) Reset() {
	*x = UpdateCategoryReq{}
	mi := &file_blog_article_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryReq) ProtoMessage() {}

func (x *UpdateCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryReq.ProtoReflect.Descriptor instead.
func (*UpdateCategoryReq) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{35}
}

func (x *UpdateCategoryReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCategoryReq) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

type UpdateCategoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryResp) Reset() {
	*x = UpdateCategoryResp{}
	mi := &file_blog_article_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryResp) ProtoMessage() {}

func (x *UpdateCategoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryResp.ProtoReflect.Descriptor instead.
func (*UpdateCategoryResp) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{36}
}

func (x *UpdateCategoryResp) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type GetCategoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryReq) Reset() {
	*x = GetCategoryReq{}
	mi := &file_blog_article_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryReq) ProtoMessage() {}

func (x *GetCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryReq.ProtoReflect.Descriptor instead.
func (*GetCategoryReq) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{37}
}

func (x *GetCategoryReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCategoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *CategoryDetails       `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryResp) Reset() {
	*x = GetCategoryResp{}
	mi := &file_blog_article_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryResp) ProtoMessage() {}

func (x *GetCategoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryResp.ProtoReflect.Descriptor instead.
func (*GetCategoryResp) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{38}
}

func (x *GetCategoryResp) GetCategory() *CategoryDetails {
	if x != nil {
		return x.Category
	}
	return nil
}

type DeletesCategoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletesCategoryReq) Reset() {
	*x = DeletesCategoryReq{}
	mi := &file_blog_article_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletesCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletesCategoryReq) ProtoMessage() {}

func (x *DeletesCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletesCategoryReq.ProtoReflect.Descriptor instead.
func (*DeletesCategoryReq) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{39}
}

func (x *DeletesCategoryReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeletesCategoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int64                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletesCategoryResp) Reset() {
	*x = DeletesCategoryResp{}
	mi := &file_blog_article_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletesCategoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletesCategoryResp) ProtoMessage() {}

func (x *DeletesCategoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletesCategoryResp.ProtoReflect.Descriptor instead.
func (*DeletesCategoryResp) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{40}
}

func (x *DeletesCategoryResp) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

type FindCategoryListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paginate      *PageReq               `protobuf:"bytes,1,opt,name=paginate,proto3" json:"paginate,omitempty"` // 分页参数
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCategoryListReq) Reset() {
	*x = FindCategoryListReq{}
	mi := &file_blog_article_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCategoryListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCategoryListReq) ProtoMessage() {}

func (x *FindCategoryListReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCategoryListReq.ProtoReflect.Descriptor instead.
func (*FindCategoryListReq) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{41}
}

func (x *FindCategoryListReq) GetPaginate() *PageReq {
	if x != nil {
		return x.Paginate
	}
	return nil
}

func (x *FindCategoryListReq) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

type FindCategoryListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PageResp              `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"` // 分页信息
	List          []*CategoryDetails     `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCategoryListResp) Reset() {
	*x = FindCategoryListResp{}
	mi := &file_blog_article_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCategoryListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCategoryListResp) ProtoMessage() {}

func (x *FindCategoryListResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCategoryListResp.ProtoReflect.Descriptor instead.
func (*FindCategoryListResp) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{42}
}

func (x *FindCategoryListResp) GetPagination() *PageResp {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *FindCategoryListResp) GetList() []*CategoryDetails {
	if x != nil {
		return x.List
	}
	return nil
}

// ************* analysis 相关 *************
type AnalysisArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisArticleReq) Reset() {
	*x = AnalysisArticleReq{}
	mi := &file_blog_article_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisArticleReq) ProtoMessage() {}

func (x *AnalysisArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisArticleReq.ProtoReflect.Descriptor instead.
func (*AnalysisArticleReq) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{43}
}

type AnalysisArticleResp struct {
	state                  protoimpl.MessageState    `protogen:"open.v1"`
	ArticleCount           int64                     `protobuf:"varint,1,opt,name=article_count,json=articleCount,proto3" json:"article_count,omitempty"`
	CategoryCount          int64                     `protobuf:"varint,2,opt,name=category_count,json=categoryCount,proto3" json:"category_count,omitempty"`
	TagCount               int64                     `protobuf:"varint,3,opt,name=tag_count,json=tagCount,proto3" json:"tag_count,omitempty"`
	CategoryList           []*CategoryDetails        `protobuf:"bytes,4,rep,name=category_list,json=categoryList,proto3" json:"category_list,omitempty"`
	TagList                []*TagDetails             `protobuf:"bytes,5,rep,name=tag_list,json=tagList,proto3" json:"tag_list,omitempty"`
	ArticleRankList        []*ArticlePreview         `protobuf:"bytes,6,rep,name=article_rank_list,json=articleRankList,proto3" json:"article_rank_list,omitempty"`                      // 文章浏览排序
	ArticleDailyStatistics []*ArticleDailyStatistics `protobuf:"bytes,7,rep,name=article_daily_statistics,json=articleDailyStatistics,proto3" json:"article_daily_statistics,omitempty"` // 每日文章数量统计
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AnalysisArticleResp) Reset() {
	*x = AnalysisArticleResp{}
	mi := &file_blog_article_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisArticleResp) ProtoMessage() {}

func (x *AnalysisArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisArticleResp.ProtoReflect.Descriptor instead.
func (*AnalysisArticleResp) Descriptor() ([]byte, []int) {
	return file_blog_article_proto_rawDescGZIP(), []int{44}
}

func (x *AnalysisArticleResp) GetArticleCount() int64 {
	if x != nil {
		return x.ArticleCount
	}
	return 0
}

func (x *AnalysisArticleResp) GetCategoryCount() int64 {
	if x != nil {
		return x.CategoryCount
	}
	return 0
}

func (x *AnalysisArticleResp) GetTagCount() int64 {
	if x != nil {
		return x.TagCount
	}
	return 0
}

func (x *AnalysisArticleResp) GetCategoryList() []*CategoryDetails {
	if x != nil {
		return x.CategoryList
	}
	return nil
}

func (x *AnalysisArticleResp) GetTagList() []*TagDetails {
	if x != nil {
		return x.TagList
	}
	return nil
}

func (x *AnalysisArticleResp) GetArticleRankList() []*ArticlePreview {
	if x != nil {
		return x.ArticleRankList
	}
	return nil
}

func (x *AnalysisArticleResp) GetArticleDailyStatistics() []*ArticleDailyStatistics {
	if x != nil {
		return x.ArticleDailyStatistics
	}
	return nil
}

var File_blog_article_proto protoreflect.FileDescriptor

const file_blog_article_proto_rawDesc = "" +
	"\n" +
	"\x12blog/article.proto\x12\n" +
	"articlerpc\"P\n" +
	"\aPageReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x14\n" +
	"\x05sorts\x18\x03 \x03(\tR\x05sorts\"Q\n" +
	"\bPageResp\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"\xc7\x01\n" +
	"\x0eArticlePreview\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rarticle_cover\x18\x04 \x01(\tR\farticleCover\x12#\n" +
	"\rarticle_title\x18\x05 \x01(\tR\farticleTitle\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"like_count\x18\x10 \x01(\x03R\tlikeCount\x12\x1d\n" +
	"\n" +
	"view_count\x18\x11 \x01(\x03R\tviewCount\"F\n" +
	"\x0fArticleCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\"'\n" +
	"\n" +
	"ArticleTag\x12\x19\n" +
	"\btag_name\x18\x01 \x01(\tR\atagName\"\xc7\x04\n" +
	"\x0eArticleDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x03R\n" +
	"categoryId\x12#\n" +
	"\rarticle_cover\x18\x04 \x01(\tR\farticleCover\x12#\n" +
	"\rarticle_title\x18\x05 \x01(\tR\farticleTitle\x12'\n" +
	"\x0farticle_content\x18\x06 \x01(\tR\x0earticleContent\x12!\n" +
	"\farticle_type\x18\a \x01(\x03R\varticleType\x12!\n" +
	"\foriginal_url\x18\b \x01(\tR\voriginalUrl\x12\x15\n" +
	"\x06is_top\x18\t \x01(\bR\x05isTop\x12\x1b\n" +
	"\tis_delete\x18\n" +
	" \x01(\bR\bisDelete\x12\x16\n" +
	"\x06status\x18\v \x01(\x03R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\x03R\tupdatedAt\x127\n" +
	"\bcategory\x18\x0e \x01(\v2\x1b.articlerpc.ArticleCategoryR\bcategory\x121\n" +
	"\btag_list\x18\x0f \x03(\v2\x16.articlerpc.ArticleTagR\atagList\x12\x1d\n" +
	"\n" +
	"like_count\x18\x10 \x01(\x03R\tlikeCount\x12\x1d\n" +
	"\n" +
	"view_count\x18\x11 \x01(\x03R\tviewCount\"}\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03R\tupdatedAt\"\xa9\x01\n" +
	"\x0fCategoryDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03R\tupdatedAt\x12#\n" +
	"\rarticle_count\x18\x05 \x01(\x03R\farticleCount\"L\n" +
	"\n" +
	"TagDetails\x12\x19\n" +
	"\btag_name\x18\x01 \x01(\tR\atagName\x12#\n" +
	"\rarticle_count\x18\x02 \x01(\x03R\farticleCount\"B\n" +
	"\x16ArticleDailyStatistics\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\xe9\x02\n" +
	"\rAddArticleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rarticle_cover\x18\x04 \x01(\tR\farticleCover\x12#\n" +
	"\rarticle_title\x18\x05 \x01(\tR\farticleTitle\x12'\n" +
	"\x0farticle_content\x18\x06 \x01(\tR\x0earticleContent\x12!\n" +
	"\farticle_type\x18\a \x01(\x03R\varticleType\x12!\n" +
	"\foriginal_url\x18\b \x01(\tR\voriginalUrl\x12\x15\n" +
	"\x06is_top\x18\t \x01(\bR\x05isTop\x12\x16\n" +
	"\x06status\x18\v \x01(\x03R\x06status\x12#\n" +
	"\rcategory_name\x18\x0f \x01(\tR\fcategoryName\x12\"\n" +
	"\rtag_name_list\x18\x10 \x03(\tR\vtagNameList\"F\n" +
	"\x0eAddArticleResp\x124\n" +
	"\aarticle\x18\x01 \x01(\v2\x1a.articlerpc.ArticlePreviewR\aarticle\"\xec\x02\n" +
	"\x10UpdateArticleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rarticle_cover\x18\x04 \x01(\tR\farticleCover\x12#\n" +
	"\rarticle_title\x18\x05 \x01(\tR\farticleTitle\x12'\n" +
	"\x0farticle_content\x18\x06 \x01(\tR\x0earticleContent\x12!\n" +
	"\farticle_type\x18\a \x01(\x03R\varticleType\x12!\n" +
	"\foriginal_url\x18\b \x01(\tR\voriginalUrl\x12\x15\n" +
	"\x06is_top\x18\t \x01(\bR\x05isTop\x12\x16\n" +
	"\x06status\x18\v \x01(\x03R\x06status\x12#\n" +
	"\rcategory_name\x18\x0f \x01(\tR\fcategoryName\x12\"\n" +
	"\rtag_name_list\x18\x10 \x03(\tR\vtagNameList\"I\n" +
	"\x11UpdateArticleResp\x124\n" +
	"\aarticle\x18\x01 \x01(\v2\x1a.articlerpc.ArticlePreviewR\aarticle\"T\n" +
	"\x16UpdateArticleDeleteReq\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12\x1b\n" +
	"\tis_delete\x18\x02 \x01(\bR\bisDelete\"O\n" +
	"\x17UpdateArticleDeleteResp\x124\n" +
	"\aarticle\x18\x01 \x01(\v2\x1a.articlerpc.ArticlePreviewR\aarticle\"K\n" +
	"\x13UpdateArticleTopReq\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12\x15\n" +
	"\x06is_top\x18\x02 \x01(\bR\x05isTop\"L\n" +
	"\x14UpdateArticleTopResp\x124\n" +
	"\aarticle\x18\x01 \x01(\v2\x1a.articlerpc.ArticlePreviewR\aarticle\"\x1f\n" +
	"\rGetArticleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"F\n" +
	"\x0eGetArticleResp\x124\n" +
	"\aarticle\x18\x01 \x01(\v2\x1a.articlerpc.ArticleDetailsR\aarticle\"'\n" +
	"\x15GetArticleRelationReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xe6\x01\n" +
	"\x16GetArticleRelationResp\x12.\n" +
	"\x04last\x18\x01 \x01(\v2\x1a.articlerpc.ArticlePreviewR\x04last\x12.\n" +
	"\x04next\x18\x02 \x01(\v2\x1a.articlerpc.ArticlePreviewR\x04next\x128\n" +
	"\trecommend\x18\x03 \x03(\v2\x1a.articlerpc.ArticlePreviewR\trecommend\x122\n" +
	"\x06newest\x18\x04 \x03(\v2\x1a.articlerpc.ArticlePreviewR\x06newest\"%\n" +
	"\x11DeletesArticleReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"9\n" +
	"\x12DeletesArticleResp\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x03R\fsuccessCount\"%\n" +
	"\x13AddArticleVisitsReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x16\n" +
	"\x14AddArticleVisitsResp\" \n" +
	"\x0eLikeArticleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x11\n" +
	"\x0fLikeArticleResp\"1\n" +
	"\x16FindUserLikeArticleReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"A\n" +
	"\x13FindLikeArticleResp\x12*\n" +
	"\x11like_article_list\x18\x01 \x03(\x03R\x0flikeArticleList\"\xce\x02\n" +
	"\x12FindArticleListReq\x12/\n" +
	"\bpaginate\x18\x01 \x01(\v2\x13.articlerpc.PageReqR\bpaginate\x12#\n" +
	"\rarticle_title\x18\x02 \x01(\tR\farticleTitle\x12!\n" +
	"\farticle_type\x18\x03 \x01(\x03R\varticleType\x12#\n" +
	"\rcategory_name\x18\x04 \x01(\tR\fcategoryName\x12\x19\n" +
	"\btag_name\x18\x05 \x01(\tR\atagName\x12\x1a\n" +
	"\x06is_top\x18\x06 \x01(\bH\x00R\x05isTop\x88\x01\x01\x12 \n" +
	"\tis_delete\x18\a \x01(\bH\x01R\bisDelete\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\b \x01(\x03R\x06status\x12\x10\n" +
	"\x03ids\x18\t \x03(\x03R\x03idsB\t\n" +
	"\a_is_topB\f\n" +
	"\n" +
	"_is_delete\"{\n" +
	"\x13FindArticleListResp\x124\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x14.articlerpc.PageRespR\n" +
	"pagination\x12.\n" +
	"\x04list\x18\x02 \x03(\v2\x1a.articlerpc.ArticleDetailsR\x04list\"\x82\x01\n" +
	"\x1aFindArticlePreviewListResp\x124\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x14.articlerpc.PageRespR\n" +
	"pagination\x12.\n" +
	"\x04list\x18\x02 \x03(\v2\x1a.articlerpc.ArticlePreviewR\x04list\"E\n" +
	"\x0eAddCategoryReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\"C\n" +
	"\x0fAddCategoryResp\x120\n" +
	"\bcategory\x18\x01 \x01(\v2\x14.articlerpc.CategoryR\bcategory\"H\n" +
	"\x11UpdateCategoryReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\"F\n" +
	"\x12UpdateCategoryResp\x120\n" +
	"\bcategory\x18\x01 \x01(\v2\x14.articlerpc.CategoryR\bcategory\" \n" +
	"\x0eGetCategoryReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"J\n" +
	"\x0fGetCategoryResp\x127\n" +
	"\bcategory\x18\x01 \x01(\v2\x1b.articlerpc.CategoryDetailsR\bcategory\"&\n" +
	"\x12DeletesCategoryReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\":\n" +
	"\x13DeletesCategoryResp\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x03R\fsuccessCount\"k\n" +
	"\x13FindCategoryListReq\x12/\n" +
	"\bpaginate\x18\x01 \x01(\v2\x13.articlerpc.PageReqR\bpaginate\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\"}\n" +
	"\x14FindCategoryListResp\x124\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x14.articlerpc.PageRespR\n" +
	"pagination\x12/\n" +
	"\x04list\x18\x02 \x03(\v2\x1b.articlerpc.CategoryDetailsR\x04list\"\x14\n" +
	"\x12AnalysisArticleReq\"\x99\x03\n" +
	"\x13AnalysisArticleResp\x12#\n" +
	"\rarticle_count\x18\x01 \x01(\x03R\farticleCount\x12%\n" +
	"\x0ecategory_count\x18\x02 \x01(\x03R\rcategoryCount\x12\x1b\n" +
	"\ttag_count\x18\x03 \x01(\x03R\btagCount\x12@\n" +
	"\rcategory_list\x18\x04 \x03(\v2\x1b.articlerpc.CategoryDetailsR\fcategoryList\x121\n" +
	"\btag_list\x18\x05 \x03(\v2\x16.articlerpc.TagDetailsR\atagList\x12F\n" +
	"\x11article_rank_list\x18\x06 \x03(\v2\x1a.articlerpc.ArticlePreviewR\x0farticleRankList\x12\\\n" +
	"\x18article_daily_statistics\x18\a \x03(\v2\".articlerpc.ArticleDailyStatisticsR\x16articleDailyStatistics2\xda\v\n" +
	"\n" +
	"ArticleRpc\x12R\n" +
	"\x0fAnalysisArticle\x12\x1e.articlerpc.AnalysisArticleReq\x1a\x1f.articlerpc.AnalysisArticleResp\x12U\n" +
	"\x10AddArticleVisits\x12\x1f.articlerpc.AddArticleVisitsReq\x1a .articlerpc.AddArticleVisitsResp\x12C\n" +
	"\n" +
	"AddArticle\x12\x19.articlerpc.AddArticleReq\x1a\x1a.articlerpc.AddArticleResp\x12L\n" +
	"\rUpdateArticle\x12\x1c.articlerpc.UpdateArticleReq\x1a\x1d.articlerpc.UpdateArticleResp\x12^\n" +
	"\x13UpdateArticleDelete\x12\".articlerpc.UpdateArticleDeleteReq\x1a#.articlerpc.UpdateArticleDeleteResp\x12U\n" +
	"\x10UpdateArticleTop\x12\x1f.articlerpc.UpdateArticleTopReq\x1a .articlerpc.UpdateArticleTopResp\x12O\n" +
	"\x0eDeletesArticle\x12\x1d.articlerpc.DeletesArticleReq\x1a\x1e.articlerpc.DeletesArticleResp\x12C\n" +
	"\n" +
	"GetArticle\x12\x19.articlerpc.GetArticleReq\x1a\x1a.articlerpc.GetArticleResp\x12[\n" +
	"\x12GetArticleRelation\x12!.articlerpc.GetArticleRelationReq\x1a\".articlerpc.GetArticleRelationResp\x12R\n" +
	"\x0fFindArticleList\x12\x1e.articlerpc.FindArticleListReq\x1a\x1f.articlerpc.FindArticleListResp\x12`\n" +
	"\x16FindArticlePreviewList\x12\x1e.articlerpc.FindArticleListReq\x1a&.articlerpc.FindArticlePreviewListResp\x12F\n" +
	"\vLikeArticle\x12\x1a.articlerpc.LikeArticleReq\x1a\x1b.articlerpc.LikeArticleResp\x12Z\n" +
	"\x13FindUserLikeArticle\x12\".articlerpc.FindUserLikeArticleReq\x1a\x1f.articlerpc.FindLikeArticleResp\x12F\n" +
	"\vAddCategory\x12\x1a.articlerpc.AddCategoryReq\x1a\x1b.articlerpc.AddCategoryResp\x12O\n" +
	"\x0eUpdateCategory\x12\x1d.articlerpc.UpdateCategoryReq\x1a\x1e.articlerpc.UpdateCategoryResp\x12F\n" +
	"\vGetCategory\x12\x1a.articlerpc.GetCategoryReq\x1a\x1b.articlerpc.GetCategoryResp\x12R\n" +
	"\x0fDeletesCategory\x12\x1e.articlerpc.DeletesCategoryReq\x1a\x1f.articlerpc.DeletesCategoryResp\x12U\n" +
	"\x10FindCategoryList\x12\x1f.articlerpc.FindCategoryListReq\x1a .articlerpc.FindCategoryListRespB\x0eZ\f./articlerpcb\x06proto3"

var (
	file_blog_article_proto_rawDescOnce sync.Once
	file_blog_article_proto_rawDescData []byte
)

func file_blog_article_proto_rawDescGZIP() []byte {
	file_blog_article_proto_rawDescOnce.Do(func() {
		file_blog_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_article_proto_rawDesc), len(file_blog_article_proto_rawDesc)))
	})
	return file_blog_article_proto_rawDescData
}

var file_blog_article_proto_msgTypes = make([]protoimpl.MessageInfo, 45)
var file_blog_article_proto_goTypes = []any{
	(*PageReq)(nil),                    // 0: articlerpc.PageReq
	(*PageResp)(nil),                   // 1: articlerpc.PageResp
	(*ArticlePreview)(nil),             // 2: articlerpc.ArticlePreview
	(*ArticleCategory)(nil),            // 3: articlerpc.ArticleCategory
	(*ArticleTag)(nil),                 // 4: articlerpc.ArticleTag
	(*ArticleDetails)(nil),             // 5: articlerpc.ArticleDetails
	(*Category)(nil),                   // 6: articlerpc.Category
	(*CategoryDetails)(nil),            // 7: articlerpc.CategoryDetails
	(*TagDetails)(nil),                 // 8: articlerpc.TagDetails
	(*ArticleDailyStatistics)(nil),     // 9: articlerpc.ArticleDailyStatistics
	(*AddArticleReq)(nil),              // 10: articlerpc.AddArticleReq
	(*AddArticleResp)(nil),             // 11: articlerpc.AddArticleResp
	(*UpdateArticleReq)(nil),           // 12: articlerpc.UpdateArticleReq
	(*UpdateArticleResp)(nil),          // 13: articlerpc.UpdateArticleResp
	(*UpdateArticleDeleteReq)(nil),     // 14: articlerpc.UpdateArticleDeleteReq
	(*UpdateArticleDeleteResp)(nil),    // 15: articlerpc.UpdateArticleDeleteResp
	(*UpdateArticleTopReq)(nil),        // 16: articlerpc.UpdateArticleTopReq
	(*UpdateArticleTopResp)(nil),       // 17: articlerpc.UpdateArticleTopResp
	(*GetArticleReq)(nil),              // 18: articlerpc.GetArticleReq
	(*GetArticleResp)(nil),             // 19: articlerpc.GetArticleResp
	(*GetArticleRelationReq)(nil),      // 20: articlerpc.GetArticleRelationReq
	(*GetArticleRelationResp)(nil),     // 21: articlerpc.GetArticleRelationResp
	(*DeletesArticleReq)(nil),          // 22: articlerpc.DeletesArticleReq
	(*DeletesArticleResp)(nil),         // 23: articlerpc.DeletesArticleResp
	(*AddArticleVisitsReq)(nil),        // 24: articlerpc.AddArticleVisitsReq
	(*AddArticleVisitsResp)(nil),       // 25: articlerpc.AddArticleVisitsResp
	(*LikeArticleReq)(nil),             // 26: articlerpc.LikeArticleReq
	(*LikeArticleResp)(nil),            // 27: articlerpc.LikeArticleResp
	(*FindUserLikeArticleReq)(nil),     // 28: articlerpc.FindUserLikeArticleReq
	(*FindLikeArticleResp)(nil),        // 29: articlerpc.FindLikeArticleResp
	(*FindArticleListReq)(nil),         // 30: articlerpc.FindArticleListReq
	(*FindArticleListResp)(nil),        // 31: articlerpc.FindArticleListResp
	(*FindArticlePreviewListResp)(nil), // 32: articlerpc.FindArticlePreviewListResp
	(*AddCategoryReq)(nil),             // 33: articlerpc.AddCategoryReq
	(*AddCategoryResp)(nil),            // 34: articlerpc.AddCategoryResp
	(*UpdateCategoryReq)(nil),          // 35: articlerpc.UpdateCategoryReq
	(*UpdateCategoryResp)(nil),         // 36: articlerpc.UpdateCategoryResp
	(*GetCategoryReq)(nil),             // 37: articlerpc.GetCategoryReq
	(*GetCategoryResp)(nil),            // 38: articlerpc.GetCategoryResp
	(*DeletesCategoryReq)(nil),         // 39: articlerpc.DeletesCategoryReq
	(*DeletesCategoryResp)(nil),        // 40: articlerpc.DeletesCategoryResp
	(*FindCategoryListReq)(nil),        // 41: articlerpc.FindCategoryListReq
	(*FindCategoryListResp)(nil),       // 42: articlerpc.FindCategoryListResp
	(*AnalysisArticleReq)(nil),         // 43: articlerpc.AnalysisArticleReq
	(*AnalysisArticleResp)(nil),        // 44: articlerpc.AnalysisArticleResp
}
var file_blog_article_proto_depIdxs = []int32{
	3,  // 0: articlerpc.ArticleDetails.category:type_name -> articlerpc.ArticleCategory
	4,  // 1: articlerpc.ArticleDetails.tag_list:type_name -> articlerpc.ArticleTag
	2,  // 2: articlerpc.AddArticleResp.article:type_name -> articlerpc.ArticlePreview
	2,  // 3: articlerpc.UpdateArticleResp.article:type_name -> articlerpc.ArticlePreview
	2,  // 4: articlerpc.UpdateArticleDeleteResp.article:type_name -> articlerpc.ArticlePreview
	2,  // 5: articlerpc.UpdateArticleTopResp.article:type_name -> articlerpc.ArticlePreview
	5,  // 6: articlerpc.GetArticleResp.article:type_name -> articlerpc.ArticleDetails
	2,  // 7: articlerpc.GetArticleRelationResp.last:type_name -> articlerpc.ArticlePreview
	2,  // 8: articlerpc.GetArticleRelationResp.next:type_name -> articlerpc.ArticlePreview
	2,  // 9: articlerpc.GetArticleRelationResp.recommend:type_name -> articlerpc.ArticlePreview
	2,  // 10: articlerpc.GetArticleRelationResp.newest:type_name -> articlerpc.ArticlePreview
	0,  // 11: articlerpc.FindArticleListReq.paginate:type_name -> articlerpc.PageReq
	1,  // 12: articlerpc.FindArticleListResp.pagination:type_name -> articlerpc.PageResp
	5,  // 13: articlerpc.FindArticleListResp.list:type_name -> articlerpc.ArticleDetails
	1,  // 14: articlerpc.FindArticlePreviewListResp.pagination:type_name -> articlerpc.PageResp
	2,  // 15: articlerpc.FindArticlePreviewListResp.list:type_name -> articlerpc.ArticlePreview
	6,  // 16: articlerpc.AddCategoryResp.category:type_name -> articlerpc.Category
	6,  // 17: articlerpc.UpdateCategoryResp.category:type_name -> articlerpc.Category
	7,  // 18: articlerpc.GetCategoryResp.category:type_name -> articlerpc.CategoryDetails
	0,  // 19: articlerpc.FindCategoryListReq.paginate:type_name -> articlerpc.PageReq
	1,  // 20: articlerpc.FindCategoryListResp.pagination:type_name -> articlerpc.PageResp
	7,  // 21: articlerpc.FindCategoryListResp.list:type_name -> articlerpc.CategoryDetails
	7,  // 22: articlerpc.AnalysisArticleResp.category_list:type_name -> articlerpc.CategoryDetails
	8,  // 23: articlerpc.AnalysisArticleResp.tag_list:type_name -> articlerpc.TagDetails
	2,  // 24: articlerpc.AnalysisArticleResp.article_rank_list:type_name -> articlerpc.ArticlePreview
	9,  // 25: articlerpc.AnalysisArticleResp.article_daily_statistics:type_name -> articlerpc.ArticleDailyStatistics
	43, // 26: articlerpc.ArticleRpc.AnalysisArticle:input_type -> articlerpc.AnalysisArticleReq
	24, // 27: articlerpc.ArticleRpc.AddArticleVisits:input_type -> articlerpc.AddArticleVisitsReq
	10, // 28: articlerpc.ArticleRpc.AddArticle:input_type -> articlerpc.AddArticleReq
	12, // 29: articlerpc.ArticleRpc.UpdateArticle:input_type -> articlerpc.UpdateArticleReq
	14, // 30: articlerpc.ArticleRpc.UpdateArticleDelete:input_type -> articlerpc.UpdateArticleDeleteReq
	16, // 31: articlerpc.ArticleRpc.UpdateArticleTop:input_type -> articlerpc.UpdateArticleTopReq
	22, // 32: articlerpc.ArticleRpc.DeletesArticle:input_type -> articlerpc.DeletesArticleReq
	18, // 33: articlerpc.ArticleRpc.GetArticle:input_type -> articlerpc.GetArticleReq
	20, // 34: articlerpc.ArticleRpc.GetArticleRelation:input_type -> articlerpc.GetArticleRelationReq
	30, // 35: articlerpc.ArticleRpc.FindArticleList:input_type -> articlerpc.FindArticleListReq
	30, // 36: articlerpc.ArticleRpc.FindArticlePreviewList:input_type -> articlerpc.FindArticleListReq
	26, // 37: articlerpc.ArticleRpc.LikeArticle:input_type -> articlerpc.LikeArticleReq
	28, // 38: articlerpc.ArticleRpc.FindUserLikeArticle:input_type -> articlerpc.FindUserLikeArticleReq
	33, // 39: articlerpc.ArticleRpc.AddCategory:input_type -> articlerpc.AddCategoryReq
	35, // 40: articlerpc.ArticleRpc.UpdateCategory:input_type -> articlerpc.UpdateCategoryReq
	37, // 41: articlerpc.ArticleRpc.GetCategory:input_type -> articlerpc.GetCategoryReq
	39, // 42: articlerpc.ArticleRpc.DeletesCategory:input_type -> articlerpc.DeletesCategoryReq
	41, // 43: articlerpc.ArticleRpc.FindCategoryList:input_type -> articlerpc.FindCategoryListReq
	44, // 44: articlerpc.ArticleRpc.AnalysisArticle:output_type -> articlerpc.AnalysisArticleResp
	25, // 45: articlerpc.ArticleRpc.AddArticleVisits:output_type -> articlerpc.AddArticleVisitsResp
	11, // 46: articlerpc.ArticleRpc.AddArticle:output_type -> articlerpc.AddArticleResp
	13, // 47: articlerpc.ArticleRpc.UpdateArticle:output_type -> articlerpc.UpdateArticleResp
	15, // 48: articlerpc.ArticleRpc.UpdateArticleDelete:output_type -> articlerpc.UpdateArticleDeleteResp
	17, // 49: articlerpc.ArticleRpc.UpdateArticleTop:output_type -> articlerpc.UpdateArticleTopResp
	23, // 50: articlerpc.ArticleRpc.DeletesArticle:output_type -> articlerpc.DeletesArticleResp
	19, // 51: articlerpc.ArticleRpc.GetArticle:output_type -> articlerpc.GetArticleResp
	21, // 52: articlerpc.ArticleRpc.GetArticleRelation:output_type -> articlerpc.GetArticleRelationResp
	31, // 53: articlerpc.ArticleRpc.FindArticleList:output_type -> articlerpc.FindArticleListResp
	32, // 54: articlerpc.ArticleRpc.FindArticlePreviewList:output_type -> articlerpc.FindArticlePreviewListResp
	27, // 55: articlerpc.ArticleRpc.LikeArticle:output_type -> articlerpc.LikeArticleResp
	29, // 56: articlerpc.ArticleRpc.FindUserLikeArticle:output_type -> articlerpc.FindLikeArticleResp
	34, // 57: articlerpc.ArticleRpc.AddCategory:output_type -> articlerpc.AddCategoryResp
	36, // 58: articlerpc.ArticleRpc.UpdateCategory:output_type -> articlerpc.UpdateCategoryResp
	38, // 59: articlerpc.ArticleRpc.GetCategory:output_type -> articlerpc.GetCategoryResp
	40, // 60: articlerpc.ArticleRpc.DeletesCategory:output_type -> articlerpc.DeletesCategoryResp
	42, // 61: articlerpc.ArticleRpc.FindCategoryList:output_type -> articlerpc.FindCategoryListResp
	44, // [44:62] is the sub-list for method output_type
	26, // [26:44] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_blog_article_proto_init() }
func file_blog_article_proto_init() {
	if File_blog_article_proto != nil {
		return
	}
	file_blog_article_proto_msgTypes[30].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_article_proto_rawDesc), len(file_blog_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   45,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_article_proto_goTypes,
		DependencyIndexes: file_blog_article_proto_depIdxs,
		MessageInfos:      file_blog_article_proto_msgTypes,
	}.Build()
	File_blog_article_proto = out.File
	file_blog_article_proto_goTypes = nil
	file_blog_article_proto_depIdxs = nil
}
