// 声明 proto 语法版本，固定值

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: blog/news.proto

// proto 包名

package newsrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分页请求参数
type PageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	Sorts         []string               `protobuf:"bytes,3,rep,name=sorts,proto3" json:"sorts,omitempty"`                        // 排序字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageReq) Reset() {
	*x = PageReq{}
	mi := &file_blog_news_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageReq) ProtoMessage() {}

func (x *PageReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageReq.ProtoReflect.Descriptor instead.
func (*PageReq) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{0}
}

func (x *PageReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageReq) GetSorts() []string {
	if x != nil {
		return x.Sorts
	}
	return nil
}

// 分页响应参数
type PageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`                       // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResp) Reset() {
	*x = PageResp{}
	mi := &file_blog_news_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResp) ProtoMessage() {}

func (x *PageResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResp.ProtoReflect.Descriptor instead.
func (*PageResp) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{1}
}

func (x *PageResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageResp) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 留言信息
type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                              // 主键id
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // 用户id
	TerminalId     string                 `protobuf:"bytes,3,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`             // 终端id
	MessageContent string                 `protobuf:"bytes,4,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"` // 留言内容
	Status         int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`                                      // 状态
	CreatedAt      int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`               // 发布时间
	UpdatedAt      int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`              // 更新时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_blog_news_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Message) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *Message) GetMessageContent() string {
	if x != nil {
		return x.MessageContent
	}
	return ""
}

func (x *Message) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Message) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Message) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 评论信息
type Comment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                              // 主键
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // 评论用户id
	TerminalId     string                 `protobuf:"bytes,3,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`             // 终端id
	TopicId        int64                  `protobuf:"varint,4,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`                     // 主题id
	ParentId       int64                  `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`                  // 父评论id
	ReplyId        int64                  `protobuf:"varint,6,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`                     // 回复评论id
	ReplyUserId    string                 `protobuf:"bytes,7,opt,name=reply_user_id,json=replyUserId,proto3" json:"reply_user_id,omitempty"`        // 评论回复用户id
	CommentContent string                 `protobuf:"bytes,8,opt,name=comment_content,json=commentContent,proto3" json:"comment_content,omitempty"` // 评论内容
	Type           int64                  `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`                                          // 评论类型
	Status         int64                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`                                     // 状态
	CreatedAt      int64                  `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`              // 评论时间
	UpdatedAt      int64                  `protobuf:"varint,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`              // 更新时间
	LikeCount      int64                  `protobuf:"varint,14,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`              // 点赞数
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_blog_news_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{3}
}

func (x *Comment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Comment) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *Comment) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *Comment) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Comment) GetReplyId() int64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

func (x *Comment) GetReplyUserId() string {
	if x != nil {
		return x.ReplyUserId
	}
	return ""
}

func (x *Comment) GetCommentContent() string {
	if x != nil {
		return x.CommentContent
	}
	return ""
}

func (x *Comment) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Comment) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Comment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Comment) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Comment) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

// ************* 留言 *************
type AddMessageReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                              // 主键id
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // 用户id
	TerminalId     string                 `protobuf:"bytes,3,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`             // 终端id
	MessageContent string                 `protobuf:"bytes,4,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"` // 留言内容
	Status         int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`                                      // 状态
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddMessageReq) Reset() {
	*x = AddMessageReq{}
	mi := &file_blog_news_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMessageReq) ProtoMessage() {}

func (x *AddMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMessageReq.ProtoReflect.Descriptor instead.
func (*AddMessageReq) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{4}
}

func (x *AddMessageReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddMessageReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddMessageReq) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *AddMessageReq) GetMessageContent() string {
	if x != nil {
		return x.MessageContent
	}
	return ""
}

func (x *AddMessageReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AddMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMessageResp) Reset() {
	*x = AddMessageResp{}
	mi := &file_blog_news_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMessageResp) ProtoMessage() {}

func (x *AddMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMessageResp.ProtoReflect.Descriptor instead.
func (*AddMessageResp) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{5}
}

func (x *AddMessageResp) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type UpdateMessageReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                              // 主键id
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // 用户id
	TerminalId     string                 `protobuf:"bytes,3,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`             // 终端id
	MessageContent string                 `protobuf:"bytes,4,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"` // 留言内容
	Status         int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`                                      // 状态
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateMessageReq) Reset() {
	*x = UpdateMessageReq{}
	mi := &file_blog_news_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageReq) ProtoMessage() {}

func (x *UpdateMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageReq.ProtoReflect.Descriptor instead.
func (*UpdateMessageReq) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMessageReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMessageReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateMessageReq) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *UpdateMessageReq) GetMessageContent() string {
	if x != nil {
		return x.MessageContent
	}
	return ""
}

func (x *UpdateMessageReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageResp) Reset() {
	*x = UpdateMessageResp{}
	mi := &file_blog_news_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageResp) ProtoMessage() {}

func (x *UpdateMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageResp.ProtoReflect.Descriptor instead.
func (*UpdateMessageResp) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMessageResp) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type GetMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 主键id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageReq) Reset() {
	*x = GetMessageReq{}
	mi := &file_blog_news_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageReq) ProtoMessage() {}

func (x *GetMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageReq.ProtoReflect.Descriptor instead.
func (*GetMessageReq) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{8}
}

func (x *GetMessageReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageResp) Reset() {
	*x = GetMessageResp{}
	mi := &file_blog_news_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageResp) ProtoMessage() {}

func (x *GetMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageResp.ProtoReflect.Descriptor instead.
func (*GetMessageResp) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{9}
}

func (x *GetMessageResp) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type DeletesMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"` // id列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletesMessageReq) Reset() {
	*x = DeletesMessageReq{}
	mi := &file_blog_news_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletesMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletesMessageReq) ProtoMessage() {}

func (x *DeletesMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletesMessageReq.ProtoReflect.Descriptor instead.
func (*DeletesMessageReq) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{10}
}

func (x *DeletesMessageReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeletesMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int64                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"` // 成功数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletesMessageResp) Reset() {
	*x = DeletesMessageResp{}
	mi := &file_blog_news_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletesMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletesMessageResp) ProtoMessage() {}

func (x *DeletesMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletesMessageResp.ProtoReflect.Descriptor instead.
func (*DeletesMessageResp) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{11}
}

func (x *DeletesMessageResp) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

type FindMessageListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paginate      *PageReq               `protobuf:"bytes,1,opt,name=paginate,proto3" json:"paginate,omitempty"`           // 分页参数
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Status        int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`              // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMessageListReq) Reset() {
	*x = FindMessageListReq{}
	mi := &file_blog_news_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMessageListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMessageListReq) ProtoMessage() {}

func (x *FindMessageListReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMessageListReq.ProtoReflect.Descriptor instead.
func (*FindMessageListReq) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{12}
}

func (x *FindMessageListReq) GetPaginate() *PageReq {
	if x != nil {
		return x.Paginate
	}
	return nil
}

func (x *FindMessageListReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FindMessageListReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type FindMessageListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PageResp              `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"` // 分页信息
	List          []*Message             `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMessageListResp) Reset() {
	*x = FindMessageListResp{}
	mi := &file_blog_news_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMessageListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMessageListResp) ProtoMessage() {}

func (x *FindMessageListResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMessageListResp.ProtoReflect.Descriptor instead.
func (*FindMessageListResp) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{13}
}

func (x *FindMessageListResp) GetPagination() *PageResp {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *FindMessageListResp) GetList() []*Message {
	if x != nil {
		return x.List
	}
	return nil
}

type UpdateMessageStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"` // 主键
	Status        int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`  // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageStatusReq) Reset() {
	*x = UpdateMessageStatusReq{}
	mi := &file_blog_news_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageStatusReq) ProtoMessage() {}

func (x *UpdateMessageStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateMessageStatusReq) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateMessageStatusReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *UpdateMessageStatusReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateMessageStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int64                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"` // 成功数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageStatusResp) Reset() {
	*x = UpdateMessageStatusResp{}
	mi := &file_blog_news_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageStatusResp) ProtoMessage() {}

func (x *UpdateMessageStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageStatusResp.ProtoReflect.Descriptor instead.
func (*UpdateMessageStatusResp) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateMessageStatusResp) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

// ************* 消息管理（评论） *************
type AddCommentReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                              // 主键
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // 评论用户id
	TerminalId     string                 `protobuf:"bytes,3,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`             // 终端id
	TopicId        int64                  `protobuf:"varint,4,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`                     // 主题id
	ParentId       int64                  `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`                  // 父评论id
	ReplyId        int64                  `protobuf:"varint,6,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`                     // 回复评论id
	ReplyUserId    string                 `protobuf:"bytes,7,opt,name=reply_user_id,json=replyUserId,proto3" json:"reply_user_id,omitempty"`        // 评论回复用户id
	CommentContent string                 `protobuf:"bytes,8,opt,name=comment_content,json=commentContent,proto3" json:"comment_content,omitempty"` // 评论内容
	Type           int64                  `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`                                          // 评论类型
	Status         int64                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`                                     // 状态
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddCommentReq) Reset() {
	*x = AddCommentReq{}
	mi := &file_blog_news_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentReq) ProtoMessage() {}

func (x *AddCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentReq.ProtoReflect.Descriptor instead.
func (*AddCommentReq) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{16}
}

func (x *AddCommentReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddCommentReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddCommentReq) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *AddCommentReq) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *AddCommentReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *AddCommentReq) GetReplyId() int64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

func (x *AddCommentReq) GetReplyUserId() string {
	if x != nil {
		return x.ReplyUserId
	}
	return ""
}

func (x *AddCommentReq) GetCommentContent() string {
	if x != nil {
		return x.CommentContent
	}
	return ""
}

func (x *AddCommentReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AddCommentReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AddCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentResp) Reset() {
	*x = AddCommentResp{}
	mi := &file_blog_news_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentResp) ProtoMessage() {}

func (x *AddCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentResp.ProtoReflect.Descriptor instead.
func (*AddCommentResp) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{17}
}

func (x *AddCommentResp) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type UpdateCommentReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                              // 主键
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // 评论用户id
	TerminalId     string                 `protobuf:"bytes,3,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`             // 终端id
	TopicId        int64                  `protobuf:"varint,4,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`                     // 主题id
	ParentId       int64                  `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`                  // 父评论id
	ReplyId        int64                  `protobuf:"varint,6,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`                     // 回复评论id
	ReplyUserId    string                 `protobuf:"bytes,7,opt,name=reply_user_id,json=replyUserId,proto3" json:"reply_user_id,omitempty"`        // 评论回复用户id
	CommentContent string                 `protobuf:"bytes,8,opt,name=comment_content,json=commentContent,proto3" json:"comment_content,omitempty"` // 评论内容
	Type           int64                  `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`                                          // 评论类型
	Status         int64                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`                                     // 状态
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateCommentReq) Reset() {
	*x = UpdateCommentReq{}
	mi := &file_blog_news_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentReq) ProtoMessage() {}

func (x *UpdateCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentReq.ProtoReflect.Descriptor instead.
func (*UpdateCommentReq) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateCommentReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCommentReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateCommentReq) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *UpdateCommentReq) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *UpdateCommentReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *UpdateCommentReq) GetReplyId() int64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

func (x *UpdateCommentReq) GetReplyUserId() string {
	if x != nil {
		return x.ReplyUserId
	}
	return ""
}

func (x *UpdateCommentReq) GetCommentContent() string {
	if x != nil {
		return x.CommentContent
	}
	return ""
}

func (x *UpdateCommentReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UpdateCommentReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentResp) Reset() {
	*x = UpdateCommentResp{}
	mi := &file_blog_news_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentResp) ProtoMessage() {}

func (x *UpdateCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentResp.ProtoReflect.Descriptor instead.
func (*UpdateCommentResp) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateCommentResp) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type GetCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 主键
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentReq) Reset() {
	*x = GetCommentReq{}
	mi := &file_blog_news_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentReq) ProtoMessage() {}

func (x *GetCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentReq.ProtoReflect.Descriptor instead.
func (*GetCommentReq) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{20}
}

func (x *GetCommentReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentResp) Reset() {
	*x = GetCommentResp{}
	mi := &file_blog_news_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentResp) ProtoMessage() {}

func (x *GetCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentResp.ProtoReflect.Descriptor instead.
func (*GetCommentResp) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{21}
}

func (x *GetCommentResp) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type DeletesCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"` // id列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletesCommentReq) Reset() {
	*x = DeletesCommentReq{}
	mi := &file_blog_news_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletesCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletesCommentReq) ProtoMessage() {}

func (x *DeletesCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletesCommentReq.ProtoReflect.Descriptor instead.
func (*DeletesCommentReq) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{22}
}

func (x *DeletesCommentReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeletesCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int64                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"` // 成功数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletesCommentResp) Reset() {
	*x = DeletesCommentResp{}
	mi := &file_blog_news_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletesCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletesCommentResp) ProtoMessage() {}

func (x *DeletesCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletesCommentResp.ProtoReflect.Descriptor instead.
func (*DeletesCommentResp) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{23}
}

func (x *DeletesCommentResp) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

type UpdateCommentStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"` // 主键
	Status        int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`  // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentStatusReq) Reset() {
	*x = UpdateCommentStatusReq{}
	mi := &file_blog_news_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentStatusReq) ProtoMessage() {}

func (x *UpdateCommentStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateCommentStatusReq) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateCommentStatusReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *UpdateCommentStatusReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateCommentStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int64                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"` // 成功数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentStatusResp) Reset() {
	*x = UpdateCommentStatusResp{}
	mi := &file_blog_news_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentStatusResp) ProtoMessage() {}

func (x *UpdateCommentStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentStatusResp.ProtoReflect.Descriptor instead.
func (*UpdateCommentStatusResp) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateCommentStatusResp) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

type FindCommentListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paginate      *PageReq               `protobuf:"bytes,1,opt,name=paginate,proto3" json:"paginate,omitempty"`           // 分页参数
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Status        int64                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`              // 状态
	Type          int64                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`                  // 评论类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCommentListReq) Reset() {
	*x = FindCommentListReq{}
	mi := &file_blog_news_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCommentListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCommentListReq) ProtoMessage() {}

func (x *FindCommentListReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCommentListReq.ProtoReflect.Descriptor instead.
func (*FindCommentListReq) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{26}
}

func (x *FindCommentListReq) GetPaginate() *PageReq {
	if x != nil {
		return x.Paginate
	}
	return nil
}

func (x *FindCommentListReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FindCommentListReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FindCommentListReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type FindCommentListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PageResp              `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"` // 分页信息
	List          []*Comment             `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCommentListResp) Reset() {
	*x = FindCommentListResp{}
	mi := &file_blog_news_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCommentListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCommentListResp) ProtoMessage() {}

func (x *FindCommentListResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCommentListResp.ProtoReflect.Descriptor instead.
func (*FindCommentListResp) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{27}
}

func (x *FindCommentListResp) GetPagination() *PageResp {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *FindCommentListResp) GetList() []*Comment {
	if x != nil {
		return x.List
	}
	return nil
}

type FindCommentReplyListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paginate      *PageReq               `protobuf:"bytes,1,opt,name=paginate,proto3" json:"paginate,omitempty"`                  // 分页参数
	TopicId       int64                  `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`    // 主题id
	ParentId      int64                  `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 父评论id
	ReplyId       int64                  `protobuf:"varint,4,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`    // 回复评论id
	Type          int64                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`                         // 评论类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCommentReplyListReq) Reset() {
	*x = FindCommentReplyListReq{}
	mi := &file_blog_news_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCommentReplyListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCommentReplyListReq) ProtoMessage() {}

func (x *FindCommentReplyListReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCommentReplyListReq.ProtoReflect.Descriptor instead.
func (*FindCommentReplyListReq) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{28}
}

func (x *FindCommentReplyListReq) GetPaginate() *PageReq {
	if x != nil {
		return x.Paginate
	}
	return nil
}

func (x *FindCommentReplyListReq) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *FindCommentReplyListReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *FindCommentReplyListReq) GetReplyId() int64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

func (x *FindCommentReplyListReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type FindCommentReplyListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PageResp              `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"` // 分页信息
	List          []*Comment             `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCommentReplyListResp) Reset() {
	*x = FindCommentReplyListResp{}
	mi := &file_blog_news_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCommentReplyListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCommentReplyListResp) ProtoMessage() {}

func (x *FindCommentReplyListResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCommentReplyListResp.ProtoReflect.Descriptor instead.
func (*FindCommentReplyListResp) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{29}
}

func (x *FindCommentReplyListResp) GetPagination() *PageResp {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *FindCommentReplyListResp) GetList() []*Comment {
	if x != nil {
		return x.List
	}
	return nil
}

type FindLikeCommentResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LikeCommentList []int64                `protobuf:"varint,1,rep,packed,name=like_comment_list,json=likeCommentList,proto3" json:"like_comment_list,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FindLikeCommentResp) Reset() {
	*x = FindLikeCommentResp{}
	mi := &file_blog_news_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindLikeCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindLikeCommentResp) ProtoMessage() {}

func (x *FindLikeCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindLikeCommentResp.ProtoReflect.Descriptor instead.
func (*FindLikeCommentResp) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{30}
}

func (x *FindLikeCommentResp) GetLikeCommentList() []int64 {
	if x != nil {
		return x.LikeCommentList
	}
	return nil
}

type FindCommentReplyCountsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicIds      []int64                `protobuf:"varint,1,rep,packed,name=topic_ids,json=topicIds,proto3" json:"topic_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCommentReplyCountsReq) Reset() {
	*x = FindCommentReplyCountsReq{}
	mi := &file_blog_news_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCommentReplyCountsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCommentReplyCountsReq) ProtoMessage() {}

func (x *FindCommentReplyCountsReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCommentReplyCountsReq.ProtoReflect.Descriptor instead.
func (*FindCommentReplyCountsReq) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{31}
}

func (x *FindCommentReplyCountsReq) GetTopicIds() []int64 {
	if x != nil {
		return x.TopicIds
	}
	return nil
}

type FindCommentReplyCountsResp struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TopicCommentCounts map[int64]int64        `protobuf:"bytes,1,rep,name=topic_comment_counts,json=topicCommentCounts,proto3" json:"topic_comment_counts,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FindCommentReplyCountsResp) Reset() {
	*x = FindCommentReplyCountsResp{}
	mi := &file_blog_news_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCommentReplyCountsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCommentReplyCountsResp) ProtoMessage() {}

func (x *FindCommentReplyCountsResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCommentReplyCountsResp.ProtoReflect.Descriptor instead.
func (*FindCommentReplyCountsResp) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{32}
}

func (x *FindCommentReplyCountsResp) GetTopicCommentCounts() map[int64]int64 {
	if x != nil {
		return x.TopicCommentCounts
	}
	return nil
}

type LikeCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 评论id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentReq) Reset() {
	*x = LikeCommentReq{}
	mi := &file_blog_news_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentReq) ProtoMessage() {}

func (x *LikeCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentReq.ProtoReflect.Descriptor instead.
func (*LikeCommentReq) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{33}
}

func (x *LikeCommentReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LikeCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentResp) Reset() {
	*x = LikeCommentResp{}
	mi := &file_blog_news_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentResp) ProtoMessage() {}

func (x *LikeCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentResp.ProtoReflect.Descriptor instead.
func (*LikeCommentResp) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{34}
}

type FindUserLikeCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserLikeCommentReq) Reset() {
	*x = FindUserLikeCommentReq{}
	mi := &file_blog_news_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserLikeCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserLikeCommentReq) ProtoMessage() {}

func (x *FindUserLikeCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserLikeCommentReq.ProtoReflect.Descriptor instead.
func (*FindUserLikeCommentReq) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{35}
}

func (x *FindUserLikeCommentReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ************* 数据分析 *************
type AnalysisMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisMessageReq) Reset() {
	*x = AnalysisMessageReq{}
	mi := &file_blog_news_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisMessageReq) ProtoMessage() {}

func (x *AnalysisMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisMessageReq.ProtoReflect.Descriptor instead.
func (*AnalysisMessageReq) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{36}
}

type AnalysisMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageCount  int64                  `protobuf:"varint,1,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisMessageResp) Reset() {
	*x = AnalysisMessageResp{}
	mi := &file_blog_news_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisMessageResp) ProtoMessage() {}

func (x *AnalysisMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_news_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisMessageResp.ProtoReflect.Descriptor instead.
func (*AnalysisMessageResp) Descriptor() ([]byte, []int) {
	return file_blog_news_proto_rawDescGZIP(), []int{37}
}

func (x *AnalysisMessageResp) GetMessageCount() int64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

var File_blog_news_proto protoreflect.FileDescriptor

const file_blog_news_proto_rawDesc = "" +
	"\n" +
	"\x0fblog/news.proto\x12\anewsrpc\"P\n" +
	"\aPageReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x14\n" +
	"\x05sorts\x18\x03 \x03(\tR\x05sorts\"Q\n" +
	"\bPageResp\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"\xd2\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vterminal_id\x18\x03 \x01(\tR\n" +
	"terminalId\x12'\n" +
	"\x0fmessage_content\x18\x04 \x01(\tR\x0emessageContent\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\"\xfc\x02\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vterminal_id\x18\x03 \x01(\tR\n" +
	"terminalId\x12\x19\n" +
	"\btopic_id\x18\x04 \x01(\x03R\atopicId\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\x03R\bparentId\x12\x19\n" +
	"\breply_id\x18\x06 \x01(\x03R\areplyId\x12\"\n" +
	"\rreply_user_id\x18\a \x01(\tR\vreplyUserId\x12'\n" +
	"\x0fcomment_content\x18\b \x01(\tR\x0ecommentContent\x12\x12\n" +
	"\x04type\x18\t \x01(\x03R\x04type\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x03R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"like_count\x18\x0e \x01(\x03R\tlikeCount\"\x9a\x01\n" +
	"\rAddMessageReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vterminal_id\x18\x03 \x01(\tR\n" +
	"terminalId\x12'\n" +
	"\x0fmessage_content\x18\x04 \x01(\tR\x0emessageContent\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\"<\n" +
	"\x0eAddMessageResp\x12*\n" +
	"\amessage\x18\x01 \x01(\v2\x10.newsrpc.MessageR\amessage\"\x9d\x01\n" +
	"\x10UpdateMessageReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vterminal_id\x18\x03 \x01(\tR\n" +
	"terminalId\x12'\n" +
	"\x0fmessage_content\x18\x04 \x01(\tR\x0emessageContent\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\"?\n" +
	"\x11UpdateMessageResp\x12*\n" +
	"\amessage\x18\x01 \x01(\v2\x10.newsrpc.MessageR\amessage\"\x1f\n" +
	"\rGetMessageReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"<\n" +
	"\x0eGetMessageResp\x12*\n" +
	"\amessage\x18\x01 \x01(\v2\x10.newsrpc.MessageR\amessage\"%\n" +
	"\x11DeletesMessageReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"9\n" +
	"\x12DeletesMessageResp\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x03R\fsuccessCount\"s\n" +
	"\x12FindMessageListReq\x12,\n" +
	"\bpaginate\x18\x01 \x01(\v2\x10.newsrpc.PageReqR\bpaginate\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\"n\n" +
	"\x13FindMessageListResp\x121\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x11.newsrpc.PageRespR\n" +
	"pagination\x12$\n" +
	"\x04list\x18\x02 \x03(\v2\x10.newsrpc.MessageR\x04list\"B\n" +
	"\x16UpdateMessageStatusReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\">\n" +
	"\x17UpdateMessageStatusResp\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x03R\fsuccessCount\"\xa5\x02\n" +
	"\rAddCommentReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vterminal_id\x18\x03 \x01(\tR\n" +
	"terminalId\x12\x19\n" +
	"\btopic_id\x18\x04 \x01(\x03R\atopicId\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\x03R\bparentId\x12\x19\n" +
	"\breply_id\x18\x06 \x01(\x03R\areplyId\x12\"\n" +
	"\rreply_user_id\x18\a \x01(\tR\vreplyUserId\x12'\n" +
	"\x0fcomment_content\x18\b \x01(\tR\x0ecommentContent\x12\x12\n" +
	"\x04type\x18\t \x01(\x03R\x04type\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x03R\x06status\"<\n" +
	"\x0eAddCommentResp\x12*\n" +
	"\acomment\x18\x01 \x01(\v2\x10.newsrpc.CommentR\acomment\"\xa8\x02\n" +
	"\x10UpdateCommentReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vterminal_id\x18\x03 \x01(\tR\n" +
	"terminalId\x12\x19\n" +
	"\btopic_id\x18\x04 \x01(\x03R\atopicId\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\x03R\bparentId\x12\x19\n" +
	"\breply_id\x18\x06 \x01(\x03R\areplyId\x12\"\n" +
	"\rreply_user_id\x18\a \x01(\tR\vreplyUserId\x12'\n" +
	"\x0fcomment_content\x18\b \x01(\tR\x0ecommentContent\x12\x12\n" +
	"\x04type\x18\t \x01(\x03R\x04type\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x03R\x06status\"?\n" +
	"\x11UpdateCommentResp\x12*\n" +
	"\acomment\x18\x01 \x01(\v2\x10.newsrpc.CommentR\acomment\"\x1f\n" +
	"\rGetCommentReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"<\n" +
	"\x0eGetCommentResp\x12*\n" +
	"\acomment\x18\x01 \x01(\v2\x10.newsrpc.CommentR\acomment\"%\n" +
	"\x11DeletesCommentReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"9\n" +
	"\x12DeletesCommentResp\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x03R\fsuccessCount\"B\n" +
	"\x16UpdateCommentStatusReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\">\n" +
	"\x17UpdateCommentStatusResp\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x03R\fsuccessCount\"\x87\x01\n" +
	"\x12FindCommentListReq\x12,\n" +
	"\bpaginate\x18\x01 \x01(\v2\x10.newsrpc.PageReqR\bpaginate\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x03R\x06status\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x03R\x04type\"n\n" +
	"\x13FindCommentListResp\x121\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x11.newsrpc.PageRespR\n" +
	"pagination\x12$\n" +
	"\x04list\x18\x02 \x03(\v2\x10.newsrpc.CommentR\x04list\"\xae\x01\n" +
	"\x17FindCommentReplyListReq\x12,\n" +
	"\bpaginate\x18\x01 \x01(\v2\x10.newsrpc.PageReqR\bpaginate\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\x03R\atopicId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\x03R\bparentId\x12\x19\n" +
	"\breply_id\x18\x04 \x01(\x03R\areplyId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x03R\x04type\"s\n" +
	"\x18FindCommentReplyListResp\x121\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x11.newsrpc.PageRespR\n" +
	"pagination\x12$\n" +
	"\x04list\x18\x02 \x03(\v2\x10.newsrpc.CommentR\x04list\"A\n" +
	"\x13FindLikeCommentResp\x12*\n" +
	"\x11like_comment_list\x18\x01 \x03(\x03R\x0flikeCommentList\"8\n" +
	"\x19FindCommentReplyCountsReq\x12\x1b\n" +
	"\ttopic_ids\x18\x01 \x03(\x03R\btopicIds\"\xd2\x01\n" +
	"\x1aFindCommentReplyCountsResp\x12m\n" +
	"\x14topic_comment_counts\x18\x01 \x03(\v2;.newsrpc.FindCommentReplyCountsResp.TopicCommentCountsEntryR\x12topicCommentCounts\x1aE\n" +
	"\x17TopicCommentCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\" \n" +
	"\x0eLikeCommentReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x11\n" +
	"\x0fLikeCommentResp\"1\n" +
	"\x16FindUserLikeCommentReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x14\n" +
	"\x12AnalysisMessageReq\":\n" +
	"\x13AnalysisMessageResp\x12#\n" +
	"\rmessage_count\x18\x01 \x01(\x03R\fmessageCount2\xa1\n" +
	"\n" +
	"\aNewsRpc\x12L\n" +
	"\x0fAnalysisMessage\x12\x1b.newsrpc.AnalysisMessageReq\x1a\x1c.newsrpc.AnalysisMessageResp\x12=\n" +
	"\n" +
	"AddMessage\x12\x16.newsrpc.AddMessageReq\x1a\x17.newsrpc.AddMessageResp\x12F\n" +
	"\rUpdateMessage\x12\x19.newsrpc.UpdateMessageReq\x1a\x1a.newsrpc.UpdateMessageResp\x12=\n" +
	"\n" +
	"GetMessage\x12\x16.newsrpc.GetMessageReq\x1a\x17.newsrpc.GetMessageResp\x12I\n" +
	"\x0eDeletesMessage\x12\x1a.newsrpc.DeletesMessageReq\x1a\x1b.newsrpc.DeletesMessageResp\x12L\n" +
	"\x0fFindMessageList\x12\x1b.newsrpc.FindMessageListReq\x1a\x1c.newsrpc.FindMessageListResp\x12X\n" +
	"\x13UpdateMessageStatus\x12\x1f.newsrpc.UpdateMessageStatusReq\x1a .newsrpc.UpdateMessageStatusResp\x12=\n" +
	"\n" +
	"AddComment\x12\x16.newsrpc.AddCommentReq\x1a\x17.newsrpc.AddCommentResp\x12F\n" +
	"\rUpdateComment\x12\x19.newsrpc.UpdateCommentReq\x1a\x1a.newsrpc.UpdateCommentResp\x12=\n" +
	"\n" +
	"GetComment\x12\x16.newsrpc.GetCommentReq\x1a\x17.newsrpc.GetCommentResp\x12I\n" +
	"\x0eDeletesComment\x12\x1a.newsrpc.DeletesCommentReq\x1a\x1b.newsrpc.DeletesCommentResp\x12L\n" +
	"\x0fFindCommentList\x12\x1b.newsrpc.FindCommentListReq\x1a\x1c.newsrpc.FindCommentListResp\x12[\n" +
	"\x14FindCommentReplyList\x12 .newsrpc.FindCommentReplyListReq\x1a!.newsrpc.FindCommentReplyListResp\x12a\n" +
	"\x16FindCommentReplyCounts\x12\".newsrpc.FindCommentReplyCountsReq\x1a#.newsrpc.FindCommentReplyCountsResp\x12X\n" +
	"\x13UpdateCommentStatus\x12\x1f.newsrpc.UpdateCommentStatusReq\x1a .newsrpc.UpdateCommentStatusResp\x12@\n" +
	"\vLikeComment\x12\x17.newsrpc.LikeCommentReq\x1a\x18.newsrpc.LikeCommentResp\x12T\n" +
	"\x13FindUserLikeComment\x12\x1f.newsrpc.FindUserLikeCommentReq\x1a\x1c.newsrpc.FindLikeCommentRespB\vZ\t./newsrpcb\x06proto3"

var (
	file_blog_news_proto_rawDescOnce sync.Once
	file_blog_news_proto_rawDescData []byte
)

func file_blog_news_proto_rawDescGZIP() []byte {
	file_blog_news_proto_rawDescOnce.Do(func() {
		file_blog_news_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_news_proto_rawDesc), len(file_blog_news_proto_rawDesc)))
	})
	return file_blog_news_proto_rawDescData
}

var file_blog_news_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_blog_news_proto_goTypes = []any{
	(*PageReq)(nil),                    // 0: newsrpc.PageReq
	(*PageResp)(nil),                   // 1: newsrpc.PageResp
	(*Message)(nil),                    // 2: newsrpc.Message
	(*Comment)(nil),                    // 3: newsrpc.Comment
	(*AddMessageReq)(nil),              // 4: newsrpc.AddMessageReq
	(*AddMessageResp)(nil),             // 5: newsrpc.AddMessageResp
	(*UpdateMessageReq)(nil),           // 6: newsrpc.UpdateMessageReq
	(*UpdateMessageResp)(nil),          // 7: newsrpc.UpdateMessageResp
	(*GetMessageReq)(nil),              // 8: newsrpc.GetMessageReq
	(*GetMessageResp)(nil),             // 9: newsrpc.GetMessageResp
	(*DeletesMessageReq)(nil),          // 10: newsrpc.DeletesMessageReq
	(*DeletesMessageResp)(nil),         // 11: newsrpc.DeletesMessageResp
	(*FindMessageListReq)(nil),         // 12: newsrpc.FindMessageListReq
	(*FindMessageListResp)(nil),        // 13: newsrpc.FindMessageListResp
	(*UpdateMessageStatusReq)(nil),     // 14: newsrpc.UpdateMessageStatusReq
	(*UpdateMessageStatusResp)(nil),    // 15: newsrpc.UpdateMessageStatusResp
	(*AddCommentReq)(nil),              // 16: newsrpc.AddCommentReq
	(*AddCommentResp)(nil),             // 17: newsrpc.AddCommentResp
	(*UpdateCommentReq)(nil),           // 18: newsrpc.UpdateCommentReq
	(*UpdateCommentResp)(nil),          // 19: newsrpc.UpdateCommentResp
	(*GetCommentReq)(nil),              // 20: newsrpc.GetCommentReq
	(*GetCommentResp)(nil),             // 21: newsrpc.GetCommentResp
	(*DeletesCommentReq)(nil),          // 22: newsrpc.DeletesCommentReq
	(*DeletesCommentResp)(nil),         // 23: newsrpc.DeletesCommentResp
	(*UpdateCommentStatusReq)(nil),     // 24: newsrpc.UpdateCommentStatusReq
	(*UpdateCommentStatusResp)(nil),    // 25: newsrpc.UpdateCommentStatusResp
	(*FindCommentListReq)(nil),         // 26: newsrpc.FindCommentListReq
	(*FindCommentListResp)(nil),        // 27: newsrpc.FindCommentListResp
	(*FindCommentReplyListReq)(nil),    // 28: newsrpc.FindCommentReplyListReq
	(*FindCommentReplyListResp)(nil),   // 29: newsrpc.FindCommentReplyListResp
	(*FindLikeCommentResp)(nil),        // 30: newsrpc.FindLikeCommentResp
	(*FindCommentReplyCountsReq)(nil),  // 31: newsrpc.FindCommentReplyCountsReq
	(*FindCommentReplyCountsResp)(nil), // 32: newsrpc.FindCommentReplyCountsResp
	(*LikeCommentReq)(nil),             // 33: newsrpc.LikeCommentReq
	(*LikeCommentResp)(nil),            // 34: newsrpc.LikeCommentResp
	(*FindUserLikeCommentReq)(nil),     // 35: newsrpc.FindUserLikeCommentReq
	(*AnalysisMessageReq)(nil),         // 36: newsrpc.AnalysisMessageReq
	(*AnalysisMessageResp)(nil),        // 37: newsrpc.AnalysisMessageResp
	nil,                                // 38: newsrpc.FindCommentReplyCountsResp.TopicCommentCountsEntry
}
var file_blog_news_proto_depIdxs = []int32{
	2,  // 0: newsrpc.AddMessageResp.message:type_name -> newsrpc.Message
	2,  // 1: newsrpc.UpdateMessageResp.message:type_name -> newsrpc.Message
	2,  // 2: newsrpc.GetMessageResp.message:type_name -> newsrpc.Message
	0,  // 3: newsrpc.FindMessageListReq.paginate:type_name -> newsrpc.PageReq
	1,  // 4: newsrpc.FindMessageListResp.pagination:type_name -> newsrpc.PageResp
	2,  // 5: newsrpc.FindMessageListResp.list:type_name -> newsrpc.Message
	3,  // 6: newsrpc.AddCommentResp.comment:type_name -> newsrpc.Comment
	3,  // 7: newsrpc.UpdateCommentResp.comment:type_name -> newsrpc.Comment
	3,  // 8: newsrpc.GetCommentResp.comment:type_name -> newsrpc.Comment
	0,  // 9: newsrpc.FindCommentListReq.paginate:type_name -> newsrpc.PageReq
	1,  // 10: newsrpc.FindCommentListResp.pagination:type_name -> newsrpc.PageResp
	3,  // 11: newsrpc.FindCommentListResp.list:type_name -> newsrpc.Comment
	0,  // 12: newsrpc.FindCommentReplyListReq.paginate:type_name -> newsrpc.PageReq
	1,  // 13: newsrpc.FindCommentReplyListResp.pagination:type_name -> newsrpc.PageResp
	3,  // 14: newsrpc.FindCommentReplyListResp.list:type_name -> newsrpc.Comment
	38, // 15: newsrpc.FindCommentReplyCountsResp.topic_comment_counts:type_name -> newsrpc.FindCommentReplyCountsResp.TopicCommentCountsEntry
	36, // 16: newsrpc.NewsRpc.AnalysisMessage:input_type -> newsrpc.AnalysisMessageReq
	4,  // 17: newsrpc.NewsRpc.AddMessage:input_type -> newsrpc.AddMessageReq
	6,  // 18: newsrpc.NewsRpc.UpdateMessage:input_type -> newsrpc.UpdateMessageReq
	8,  // 19: newsrpc.NewsRpc.GetMessage:input_type -> newsrpc.GetMessageReq
	10, // 20: newsrpc.NewsRpc.DeletesMessage:input_type -> newsrpc.DeletesMessageReq
	12, // 21: newsrpc.NewsRpc.FindMessageList:input_type -> newsrpc.FindMessageListReq
	14, // 22: newsrpc.NewsRpc.UpdateMessageStatus:input_type -> newsrpc.UpdateMessageStatusReq
	16, // 23: newsrpc.NewsRpc.AddComment:input_type -> newsrpc.AddCommentReq
	18, // 24: newsrpc.NewsRpc.UpdateComment:input_type -> newsrpc.UpdateCommentReq
	20, // 25: newsrpc.NewsRpc.GetComment:input_type -> newsrpc.GetCommentReq
	22, // 26: newsrpc.NewsRpc.DeletesComment:input_type -> newsrpc.DeletesCommentReq
	26, // 27: newsrpc.NewsRpc.FindCommentList:input_type -> newsrpc.FindCommentListReq
	28, // 28: newsrpc.NewsRpc.FindCommentReplyList:input_type -> newsrpc.FindCommentReplyListReq
	31, // 29: newsrpc.NewsRpc.FindCommentReplyCounts:input_type -> newsrpc.FindCommentReplyCountsReq
	24, // 30: newsrpc.NewsRpc.UpdateCommentStatus:input_type -> newsrpc.UpdateCommentStatusReq
	33, // 31: newsrpc.NewsRpc.LikeComment:input_type -> newsrpc.LikeCommentReq
	35, // 32: newsrpc.NewsRpc.FindUserLikeComment:input_type -> newsrpc.FindUserLikeCommentReq
	37, // 33: newsrpc.NewsRpc.AnalysisMessage:output_type -> newsrpc.AnalysisMessageResp
	5,  // 34: newsrpc.NewsRpc.AddMessage:output_type -> newsrpc.AddMessageResp
	7,  // 35: newsrpc.NewsRpc.UpdateMessage:output_type -> newsrpc.UpdateMessageResp
	9,  // 36: newsrpc.NewsRpc.GetMessage:output_type -> newsrpc.GetMessageResp
	11, // 37: newsrpc.NewsRpc.DeletesMessage:output_type -> newsrpc.DeletesMessageResp
	13, // 38: newsrpc.NewsRpc.FindMessageList:output_type -> newsrpc.FindMessageListResp
	15, // 39: newsrpc.NewsRpc.UpdateMessageStatus:output_type -> newsrpc.UpdateMessageStatusResp
	17, // 40: newsrpc.NewsRpc.AddComment:output_type -> newsrpc.AddCommentResp
	19, // 41: newsrpc.NewsRpc.UpdateComment:output_type -> newsrpc.UpdateCommentResp
	21, // 42: newsrpc.NewsRpc.GetComment:output_type -> newsrpc.GetCommentResp
	23, // 43: newsrpc.NewsRpc.DeletesComment:output_type -> newsrpc.DeletesCommentResp
	27, // 44: newsrpc.NewsRpc.FindCommentList:output_type -> newsrpc.FindCommentListResp
	29, // 45: newsrpc.NewsRpc.FindCommentReplyList:output_type -> newsrpc.FindCommentReplyListResp
	32, // 46: newsrpc.NewsRpc.FindCommentReplyCounts:output_type -> newsrpc.FindCommentReplyCountsResp
	25, // 47: newsrpc.NewsRpc.UpdateCommentStatus:output_type -> newsrpc.UpdateCommentStatusResp
	34, // 48: newsrpc.NewsRpc.LikeComment:output_type -> newsrpc.LikeCommentResp
	30, // 49: newsrpc.NewsRpc.FindUserLikeComment:output_type -> newsrpc.FindLikeCommentResp
	33, // [33:50] is the sub-list for method output_type
	16, // [16:33] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_blog_news_proto_init() }
func file_blog_news_proto_init() {
	if File_blog_news_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_news_proto_rawDesc), len(file_blog_news_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_news_proto_goTypes,
		DependencyIndexes: file_blog_news_proto_depIdxs,
		MessageInfos:      file_blog_news_proto_msgTypes,
	}.Build()
	File_blog_news_proto = out.File
	file_blog_news_proto_goTypes = nil
	file_blog_news_proto_depIdxs = nil
}
