// 声明 proto 语法版本，固定值

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: blog/permission.proto

// proto 包名

package permissionrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PermissionRpc_AddApi_FullMethodName            = "/permissionrpc.PermissionRpc/AddApi"
	PermissionRpc_UpdateApi_FullMethodName         = "/permissionrpc.PermissionRpc/UpdateApi"
	PermissionRpc_DeletesApi_FullMethodName        = "/permissionrpc.PermissionRpc/DeletesApi"
	PermissionRpc_FindApiList_FullMethodName       = "/permissionrpc.PermissionRpc/FindApiList"
	PermissionRpc_SyncApiList_FullMethodName       = "/permissionrpc.PermissionRpc/SyncApiList"
	PermissionRpc_CleanApiList_FullMethodName      = "/permissionrpc.PermissionRpc/CleanApiList"
	PermissionRpc_FindAllApi_FullMethodName        = "/permissionrpc.PermissionRpc/FindAllApi"
	PermissionRpc_FindRoleList_FullMethodName      = "/permissionrpc.PermissionRpc/FindRoleList"
	PermissionRpc_FindAllRole_FullMethodName       = "/permissionrpc.PermissionRpc/FindAllRole"
	PermissionRpc_UpdateRoleApis_FullMethodName    = "/permissionrpc.PermissionRpc/UpdateRoleApis"
	PermissionRpc_FindRoleResources_FullMethodName = "/permissionrpc.PermissionRpc/FindRoleResources"
	PermissionRpc_UpdateUserRole_FullMethodName    = "/permissionrpc.PermissionRpc/UpdateUserRole"
	PermissionRpc_FindUserApis_FullMethodName      = "/permissionrpc.PermissionRpc/FindUserApis"
	PermissionRpc_FindUserRoles_FullMethodName     = "/permissionrpc.PermissionRpc/FindUserRoles"
)

// PermissionRpcClient is the client API for PermissionRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PermissionRpcClient interface {
	// 创建接口
	AddApi(ctx context.Context, in *AddApiReq, opts ...grpc.CallOption) (*AddApiResp, error)
	// 更新接口
	UpdateApi(ctx context.Context, in *UpdateApiReq, opts ...grpc.CallOption) (*UpdateApiResp, error)
	// 删除接口
	DeletesApi(ctx context.Context, in *DeletesApiReq, opts ...grpc.CallOption) (*DeletesApiResp, error)
	// 查询接口列表
	FindApiList(ctx context.Context, in *FindApiListReq, opts ...grpc.CallOption) (*FindApiListResp, error)
	// 同步接口列表
	SyncApiList(ctx context.Context, in *SyncApiListReq, opts ...grpc.CallOption) (*SyncApiListResp, error)
	// 清空接口列表
	CleanApiList(ctx context.Context, in *CleanApiListReq, opts ...grpc.CallOption) (*CleanApiListResp, error)
	// 查找所有接口
	FindAllApi(ctx context.Context, in *FindAllApiReq, opts ...grpc.CallOption) (*FindAllApiResp, error)
	// 查询角色列表
	FindRoleList(ctx context.Context, in *FindRoleListReq, opts ...grpc.CallOption) (*FindRoleListResp, error)
	// 查询所有角色
	FindAllRole(ctx context.Context, in *FindAllRoleReq, opts ...grpc.CallOption) (*FindAllRoleResp, error)
	// 更新角色资源
	UpdateRoleApis(ctx context.Context, in *UpdateRoleApisReq, opts ...grpc.CallOption) (*UpdateRoleApisResp, error)
	// 查询角色资源权限
	FindRoleResources(ctx context.Context, in *FindRoleResourcesReq, opts ...grpc.CallOption) (*FindRoleResourcesResp, error)
	// 修改用户角色
	UpdateUserRole(ctx context.Context, in *UpdateUserRoleReq, opts ...grpc.CallOption) (*UpdateUserRoleResp, error)
	// 获取用户接口权限
	FindUserApis(ctx context.Context, in *FindUserApisReq, opts ...grpc.CallOption) (*FindUserApisResp, error)
	// 获取用户角色信息
	FindUserRoles(ctx context.Context, in *FindUserRolesReq, opts ...grpc.CallOption) (*FindUserRolesResp, error)
}

type permissionRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewPermissionRpcClient(cc grpc.ClientConnInterface) PermissionRpcClient {
	return &permissionRpcClient{cc}
}

func (c *permissionRpcClient) AddApi(ctx context.Context, in *AddApiReq, opts ...grpc.CallOption) (*AddApiResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddApiResp)
	err := c.cc.Invoke(ctx, PermissionRpc_AddApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) UpdateApi(ctx context.Context, in *UpdateApiReq, opts ...grpc.CallOption) (*UpdateApiResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateApiResp)
	err := c.cc.Invoke(ctx, PermissionRpc_UpdateApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) DeletesApi(ctx context.Context, in *DeletesApiReq, opts ...grpc.CallOption) (*DeletesApiResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletesApiResp)
	err := c.cc.Invoke(ctx, PermissionRpc_DeletesApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) FindApiList(ctx context.Context, in *FindApiListReq, opts ...grpc.CallOption) (*FindApiListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindApiListResp)
	err := c.cc.Invoke(ctx, PermissionRpc_FindApiList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) SyncApiList(ctx context.Context, in *SyncApiListReq, opts ...grpc.CallOption) (*SyncApiListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncApiListResp)
	err := c.cc.Invoke(ctx, PermissionRpc_SyncApiList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) CleanApiList(ctx context.Context, in *CleanApiListReq, opts ...grpc.CallOption) (*CleanApiListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanApiListResp)
	err := c.cc.Invoke(ctx, PermissionRpc_CleanApiList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) FindAllApi(ctx context.Context, in *FindAllApiReq, opts ...grpc.CallOption) (*FindAllApiResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindAllApiResp)
	err := c.cc.Invoke(ctx, PermissionRpc_FindAllApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) FindRoleList(ctx context.Context, in *FindRoleListReq, opts ...grpc.CallOption) (*FindRoleListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindRoleListResp)
	err := c.cc.Invoke(ctx, PermissionRpc_FindRoleList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) FindAllRole(ctx context.Context, in *FindAllRoleReq, opts ...grpc.CallOption) (*FindAllRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindAllRoleResp)
	err := c.cc.Invoke(ctx, PermissionRpc_FindAllRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) UpdateRoleApis(ctx context.Context, in *UpdateRoleApisReq, opts ...grpc.CallOption) (*UpdateRoleApisResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRoleApisResp)
	err := c.cc.Invoke(ctx, PermissionRpc_UpdateRoleApis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) FindRoleResources(ctx context.Context, in *FindRoleResourcesReq, opts ...grpc.CallOption) (*FindRoleResourcesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindRoleResourcesResp)
	err := c.cc.Invoke(ctx, PermissionRpc_FindRoleResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) UpdateUserRole(ctx context.Context, in *UpdateUserRoleReq, opts ...grpc.CallOption) (*UpdateUserRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserRoleResp)
	err := c.cc.Invoke(ctx, PermissionRpc_UpdateUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) FindUserApis(ctx context.Context, in *FindUserApisReq, opts ...grpc.CallOption) (*FindUserApisResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindUserApisResp)
	err := c.cc.Invoke(ctx, PermissionRpc_FindUserApis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionRpcClient) FindUserRoles(ctx context.Context, in *FindUserRolesReq, opts ...grpc.CallOption) (*FindUserRolesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindUserRolesResp)
	err := c.cc.Invoke(ctx, PermissionRpc_FindUserRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermissionRpcServer is the server API for PermissionRpc service.
// All implementations must embed UnimplementedPermissionRpcServer
// for forward compatibility.
type PermissionRpcServer interface {
	// 创建接口
	AddApi(context.Context, *AddApiReq) (*AddApiResp, error)
	// 更新接口
	UpdateApi(context.Context, *UpdateApiReq) (*UpdateApiResp, error)
	// 删除接口
	DeletesApi(context.Context, *DeletesApiReq) (*DeletesApiResp, error)
	// 查询接口列表
	FindApiList(context.Context, *FindApiListReq) (*FindApiListResp, error)
	// 同步接口列表
	SyncApiList(context.Context, *SyncApiListReq) (*SyncApiListResp, error)
	// 清空接口列表
	CleanApiList(context.Context, *CleanApiListReq) (*CleanApiListResp, error)
	// 查找所有接口
	FindAllApi(context.Context, *FindAllApiReq) (*FindAllApiResp, error)
	// 查询角色列表
	FindRoleList(context.Context, *FindRoleListReq) (*FindRoleListResp, error)
	// 查询所有角色
	FindAllRole(context.Context, *FindAllRoleReq) (*FindAllRoleResp, error)
	// 更新角色资源
	UpdateRoleApis(context.Context, *UpdateRoleApisReq) (*UpdateRoleApisResp, error)
	// 查询角色资源权限
	FindRoleResources(context.Context, *FindRoleResourcesReq) (*FindRoleResourcesResp, error)
	// 修改用户角色
	UpdateUserRole(context.Context, *UpdateUserRoleReq) (*UpdateUserRoleResp, error)
	// 获取用户接口权限
	FindUserApis(context.Context, *FindUserApisReq) (*FindUserApisResp, error)
	// 获取用户角色信息
	FindUserRoles(context.Context, *FindUserRolesReq) (*FindUserRolesResp, error)
	mustEmbedUnimplementedPermissionRpcServer()
}

// UnimplementedPermissionRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPermissionRpcServer struct{}

func (UnimplementedPermissionRpcServer) AddApi(context.Context, *AddApiReq) (*AddApiResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddApi not implemented")
}
func (UnimplementedPermissionRpcServer) UpdateApi(context.Context, *UpdateApiReq) (*UpdateApiResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateApi not implemented")
}
func (UnimplementedPermissionRpcServer) DeletesApi(context.Context, *DeletesApiReq) (*DeletesApiResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletesApi not implemented")
}
func (UnimplementedPermissionRpcServer) FindApiList(context.Context, *FindApiListReq) (*FindApiListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FindApiList not implemented")
}
func (UnimplementedPermissionRpcServer) SyncApiList(context.Context, *SyncApiListReq) (*SyncApiListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncApiList not implemented")
}
func (UnimplementedPermissionRpcServer) CleanApiList(context.Context, *CleanApiListReq) (*CleanApiListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanApiList not implemented")
}
func (UnimplementedPermissionRpcServer) FindAllApi(context.Context, *FindAllApiReq) (*FindAllApiResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAllApi not implemented")
}
func (UnimplementedPermissionRpcServer) FindRoleList(context.Context, *FindRoleListReq) (*FindRoleListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FindRoleList not implemented")
}
func (UnimplementedPermissionRpcServer) FindAllRole(context.Context, *FindAllRoleReq) (*FindAllRoleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAllRole not implemented")
}
func (UnimplementedPermissionRpcServer) UpdateRoleApis(context.Context, *UpdateRoleApisReq) (*UpdateRoleApisResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRoleApis not implemented")
}
func (UnimplementedPermissionRpcServer) FindRoleResources(context.Context, *FindRoleResourcesReq) (*FindRoleResourcesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FindRoleResources not implemented")
}
func (UnimplementedPermissionRpcServer) UpdateUserRole(context.Context, *UpdateUserRoleReq) (*UpdateUserRoleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserRole not implemented")
}
func (UnimplementedPermissionRpcServer) FindUserApis(context.Context, *FindUserApisReq) (*FindUserApisResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FindUserApis not implemented")
}
func (UnimplementedPermissionRpcServer) FindUserRoles(context.Context, *FindUserRolesReq) (*FindUserRolesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FindUserRoles not implemented")
}
func (UnimplementedPermissionRpcServer) mustEmbedUnimplementedPermissionRpcServer() {}
func (UnimplementedPermissionRpcServer) testEmbeddedByValue()                       {}

// UnsafePermissionRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PermissionRpcServer will
// result in compilation errors.
type UnsafePermissionRpcServer interface {
	mustEmbedUnimplementedPermissionRpcServer()
}

func RegisterPermissionRpcServer(s grpc.ServiceRegistrar, srv PermissionRpcServer) {
	// If the following call panics, it indicates UnimplementedPermissionRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PermissionRpc_ServiceDesc, srv)
}

func _PermissionRpc_AddApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).AddApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_AddApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).AddApi(ctx, req.(*AddApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_UpdateApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).UpdateApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_UpdateApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).UpdateApi(ctx, req.(*UpdateApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_DeletesApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletesApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).DeletesApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_DeletesApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).DeletesApi(ctx, req.(*DeletesApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_FindApiList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindApiListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).FindApiList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_FindApiList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).FindApiList(ctx, req.(*FindApiListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_SyncApiList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncApiListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).SyncApiList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_SyncApiList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).SyncApiList(ctx, req.(*SyncApiListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_CleanApiList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanApiListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).CleanApiList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_CleanApiList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).CleanApiList(ctx, req.(*CleanApiListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_FindAllApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).FindAllApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_FindAllApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).FindAllApi(ctx, req.(*FindAllApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_FindRoleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRoleListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).FindRoleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_FindRoleList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).FindRoleList(ctx, req.(*FindRoleListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_FindAllRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).FindAllRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_FindAllRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).FindAllRole(ctx, req.(*FindAllRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_UpdateRoleApis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleApisReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).UpdateRoleApis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_UpdateRoleApis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).UpdateRoleApis(ctx, req.(*UpdateRoleApisReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_FindRoleResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRoleResourcesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).FindRoleResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_FindRoleResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).FindRoleResources(ctx, req.(*FindRoleResourcesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_UpdateUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).UpdateUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_UpdateUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).UpdateUserRole(ctx, req.(*UpdateUserRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_FindUserApis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserApisReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).FindUserApis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_FindUserApis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).FindUserApis(ctx, req.(*FindUserApisReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionRpc_FindUserRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserRolesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionRpcServer).FindUserRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionRpc_FindUserRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionRpcServer).FindUserRoles(ctx, req.(*FindUserRolesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PermissionRpc_ServiceDesc is the grpc.ServiceDesc for PermissionRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PermissionRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "permissionrpc.PermissionRpc",
	HandlerType: (*PermissionRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddApi",
			Handler:    _PermissionRpc_AddApi_Handler,
		},
		{
			MethodName: "UpdateApi",
			Handler:    _PermissionRpc_UpdateApi_Handler,
		},
		{
			MethodName: "DeletesApi",
			Handler:    _PermissionRpc_DeletesApi_Handler,
		},
		{
			MethodName: "FindApiList",
			Handler:    _PermissionRpc_FindApiList_Handler,
		},
		{
			MethodName: "SyncApiList",
			Handler:    _PermissionRpc_SyncApiList_Handler,
		},
		{
			MethodName: "CleanApiList",
			Handler:    _PermissionRpc_CleanApiList_Handler,
		},
		{
			MethodName: "FindAllApi",
			Handler:    _PermissionRpc_FindAllApi_Handler,
		},
		{
			MethodName: "FindRoleList",
			Handler:    _PermissionRpc_FindRoleList_Handler,
		},
		{
			MethodName: "FindAllRole",
			Handler:    _PermissionRpc_FindAllRole_Handler,
		},
		{
			MethodName: "UpdateRoleApis",
			Handler:    _PermissionRpc_UpdateRoleApis_Handler,
		},
		{
			MethodName: "FindRoleResources",
			Handler:    _PermissionRpc_FindRoleResources_Handler,
		},
		{
			MethodName: "UpdateUserRole",
			Handler:    _PermissionRpc_UpdateUserRole_Handler,
		},
		{
			MethodName: "FindUserApis",
			Handler:    _PermissionRpc_FindUserApis_Handler,
		},
		{
			MethodName: "FindUserRoles",
			Handler:    _PermissionRpc_FindUserRoles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog/permission.proto",
}
