DROP TRIGGER IF EXISTS trg_t_album_set_updated_at ON t_album;
DROP TRIGGER IF EXISTS trg_t_api_set_updated_at ON t_api;
DROP TRIGGER IF EXISTS trg_t_article_set_updated_at ON t_article;
DROP TRIGGER IF EXISTS trg_t_category_set_updated_at ON t_category;
DROP TRIGGER IF EXISTS trg_t_comment_set_updated_at ON t_comment;
DROP TRIGGER IF EXISTS trg_t_file_log_set_updated_at ON t_file_log;
DROP TRIGGER IF EXISTS trg_t_friend_set_updated_at ON t_friend;
DROP TRIGGER IF EXISTS trg_t_login_log_set_updated_at ON t_login_log;
DROP TRIGGER IF EXISTS trg_t_menu_set_updated_at ON t_menu;
DROP TRIGGER IF EXISTS trg_t_message_set_updated_at ON t_message;
DROP TRIGGER IF EXISTS trg_t_operation_log_set_updated_at ON t_operation_log;
DROP TRIGGER IF EXISTS trg_t_page_set_updated_at ON t_page;
DROP TRIGGER IF EXISTS trg_t_photo_set_updated_at ON t_photo;
DROP TRIGGER IF EXISTS trg_t_role_set_updated_at ON t_role;
DROP TRIGGER IF EXISTS trg_t_system_notice_set_updated_at ON t_system_notice;
DROP TRIGGER IF EXISTS trg_t_tag_set_updated_at ON t_tag;
DROP TRIGGER IF EXISTS trg_t_talk_set_updated_at ON t_talk;
DROP TRIGGER IF EXISTS trg_t_user_set_updated_at ON t_user;
DROP TRIGGER IF EXISTS trg_t_user_oauth_set_updated_at ON t_user_oauth;
DROP TRIGGER IF EXISTS trg_t_visit_daily_stats_set_updated_at ON t_visit_daily_stats;
DROP TRIGGER IF EXISTS trg_t_visit_log_set_updated_at ON t_visit_log;
DROP TRIGGER IF EXISTS trg_t_visitor_set_updated_at ON t_visitor;
DROP TRIGGER IF EXISTS trg_t_website_config_set_updated_at ON t_website_config;

DROP FUNCTION IF EXISTS set_updated_at();

DROP TABLE IF EXISTS t_role_api;
DROP TABLE IF EXISTS t_role_menu;
DROP TABLE IF EXISTS t_user_role;
DROP TABLE IF EXISTS t_user_oauth;

DROP TABLE IF EXISTS t_website_config;
DROP TABLE IF EXISTS t_visitor;
DROP TABLE IF EXISTS t_visit_log;
DROP TABLE IF EXISTS t_visit_daily_stats;
DROP TABLE IF EXISTS t_user;
DROP TABLE IF EXISTS t_talk;
DROP TABLE IF EXISTS t_tag;
DROP TABLE IF EXISTS t_system_notice;
DROP TABLE IF EXISTS t_role;
DROP TABLE IF EXISTS t_photo;
DROP TABLE IF EXISTS t_page;
DROP TABLE IF EXISTS t_operation_log;
DROP TABLE IF EXISTS t_message;
DROP TABLE IF EXISTS t_menu;
DROP TABLE IF EXISTS t_login_log;
DROP TABLE IF EXISTS t_friend;
DROP TABLE IF EXISTS t_file_log;
DROP TABLE IF EXISTS t_comment;
DROP TABLE IF EXISTS t_article;
DROP TABLE IF EXISTS t_api;
DROP TABLE IF EXISTS t_category;
DROP TABLE IF EXISTS t_album;
